// CMF Division — Cranio-Maxillofacial
export const cmf = [
  {
    maId: 'PRD-059', maName: 'MatrixMIDFACE Plating System',
    maDescription: 'Low-profile titanium plating system for midface fracture fixation and orthognathic surgery. Includes orbital floor, zygomatic, Le Fort, and nasal plates.',
    division: 'CMF', category: 'Midface Fixation', subcategory: 'Plating',
    sku: 'STR-MXMF-SYS', price: 3800.00, listPrice: 4400.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-highlights-MaxFace?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Titanium', plateThickness: '0.4–0.6 mm', screwSizes: '1.5, 2.0 mm', profiles: 'Orbital, zygomatic, Le Fort, nasal', lockingOption: 'Available' },
    regulatory: { fdaClearance: 'K200123', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400590001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['CMF', 'midface', 'plating', 'orbital', 'zygomatic'],
  },
  {
    maId: 'PRD-060', maName: 'MatrixMANDIBLE Plating System',
    maDescription: 'Comprehensive mandibular fixation system with locking and non-locking plate options. Covers simple fractures through complex reconstruction with load-bearing plates.',
    division: 'CMF', category: 'Mandible Fixation', subcategory: 'Plating',
    sku: 'STR-MXMN-SYS', price: 4200.00, listPrice: 4800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Universal%20Mandible%20and%20Fracture-1?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Titanium', plateTypes: 'Adaptation, reconstruction, condylar', screwSizes: '2.0, 2.3, 2.7 mm', lockingMechanism: 'StarDrive locking', loadBearing: 'Yes — reconstruction plates' },
    regulatory: { fdaClearance: 'K200124', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400590002', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['CMF', 'mandible', 'plating', 'reconstruction', 'fracture'],
  },
  {
    maId: 'PRD-061', maName: 'MatrixORTHOGNATHIC Fixation System',
    maDescription: 'Specialized plating system for orthognathic (jaw realignment) surgery. Purpose-designed plates for Le Fort I, sagittal split, and genioplasty procedures.',
    division: 'CMF', category: 'Orthognathic', subcategory: 'Fixation',
    sku: 'STR-MXOG-SYS', price: 3200.00, listPrice: 3700.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Universal%20Ortho-1?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { procedures: 'Le Fort I, BSSO, genioplasty', material: 'Titanium', screwSizes: '2.0 mm self-drilling', plateProfiles: 'L-plates, straight, Y-plates', customBending: 'Pre-bent anatomic' },
    regulatory: { fdaClearance: 'K200125', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400590003', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['CMF', 'orthognathic', 'jaw-surgery', 'fixation', 'Le-Fort'],
  },
  {
    maId: 'PRD-062', maName: 'VSP Virtual Surgical Planning',
    maDescription: 'Patient-specific virtual surgical planning service with 3D modeling. Engineers collaborate with surgeons to plan complex reconstructive procedures and produce custom cutting guides.',
    division: 'CMF', category: 'Digital Planning', subcategory: 'Virtual Surgical Planning',
    sku: 'STR-VSP-PLAN', price: 8500.00, listPrice: 9800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/VSP-guides-product-thumbnail?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { imaging: 'CT-based 3D modeling', collaboration: 'Web-based surgeon-engineer planning session', outputs: 'Cutting guides, plate pre-bending templates, anatomic models', turnaround: '5–7 business days', applications: 'Oncology, trauma, orthognathic, cranioplasty' },
    regulatory: { fdaClearance: 'K210123', deviceClass: 'Class II', productCode: 'QBS', gudid: '00884400590004', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['CMF', 'VSP', 'virtual-planning', '3D', 'patient-specific'],
  },
  {
    maId: 'PRD-063', maName: 'VSP Titanium Guides',
    maDescription: '3D-printed titanium patient-specific surgical guides for direct cutting and drilling. 20x stronger than traditional SLA guides for enhanced intraoperative performance.',
    division: 'CMF', category: 'Surgical Guides', subcategory: 'Patient-Specific',
    sku: 'STR-VSP-TI-GUIDE', price: 4500.00, listPrice: 5200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-categories-Orthognathic?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { material: '3D-printed titanium', strength: '20x traditional SLA', sterilization: 'Steam autoclavable', applications: 'Orthognathic, oncology, reconstruction', turnaround: '7–10 business days' },
    regulatory: { fdaClearance: 'K220234', deviceClass: 'Class II', productCode: 'QBS', gudid: '00884400590005', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 10, minOrderQuantity: 1,
    tags: ['CMF', 'VSP', 'guides', 'titanium', '3D-printed', 'patient-specific'],
  },
  {
    maId: 'PRD-064', maName: 'PEEK Customized Cranial Implant',
    maDescription: 'Patient-specific PEEK implant for cranial vault reconstruction. Individually designed to replace bone voids with 115 MPa yield strength and anatomical fit.',
    division: 'CMF', category: 'Cranial Reconstruction', subcategory: 'Custom Implants',
    sku: 'STR-PEEK-CRAN', price: 12000.00, listPrice: 14000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-PEEK?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { material: 'PEEK (polyetheretherketone)', yieldStrength: '115 MPa', wallThickness: '3.3, 4, 5, or 6 mm', design: 'CT-based patient-specific', radiolucency: 'Radiolucent', mriCompatibility: 'MR Conditional' },
    regulatory: { fdaClearance: 'K210345', deviceClass: 'Class II', productCode: 'LYZ', gudid: '00884400590006', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['CMF', 'cranial', 'PEEK', 'custom-implant', 'patient-specific'],
  },
  {
    maId: 'PRD-065', maName: 'Universal Cranial Mesh System',
    maDescription: 'Titanium cranial mesh implants in 2D and 3D configurations. Countersink screw design reduces palpability. MR Conditional for post-implant diagnostics.',
    division: 'CMF', category: 'Cranial Reconstruction', subcategory: 'Mesh Implants',
    sku: 'STR-MESH-CRAN', price: 3500.00, listPrice: 4000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-Universal-Mesh?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Titanium', configurations: '2D flat, 3D pre-formed', variants: 'Hybrid, Dynamic, Gold 3D, Silver 3D', screwType: 'Countersink self-drilling', mriCompatibility: 'MR Conditional' },
    regulatory: { fdaClearance: 'K200678', deviceClass: 'Class II', productCode: 'LYZ', gudid: '00884400590007', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['CMF', 'cranial', 'mesh', 'titanium', 'reconstruction'],
  },
  {
    maId: 'PRD-066', maName: 'TMJ Concepts Patient-Specific Implant',
    maDescription: 'Custom temporomandibular joint reconstruction prosthesis. Gold standard in TMJ reconstruction with individualized design for each patient anatomy.',
    division: 'CMF', category: 'TMJ Reconstruction', subcategory: 'Custom Implants',
    sku: 'STR-TMJ-PSI', price: 18000.00, listPrice: 21000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-TMJ-Concepts?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { fossaComponent: 'Titanium mesh with UHMWPE articulation', mandibularComponent: 'CoCrMo and Ti alloys', design: 'CT-based patient-specific', followUp: '20+ year clinical data', preference: '78% surgeon preference over off-the-shelf' },
    regulatory: { fdaClearance: 'P960014 (PMA)', deviceClass: 'Class III', productCode: 'NTJ', gudid: '00884400590008', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 21, minOrderQuantity: 1,
    tags: ['CMF', 'TMJ', 'patient-specific', 'custom', 'jaw-reconstruction'],
  },
  {
    maId: 'PRD-067', maName: 'Leibinger Micro Plating System',
    maDescription: 'Ultra-low-profile titanium micro plating system for craniofacial and pediatric fixation. 1.0 mm and 1.3 mm screw options for delicate anatomical regions.',
    division: 'CMF', category: 'Micro Fixation', subcategory: 'Plating',
    sku: 'STR-LEIB-MICRO', price: 2800.00, listPrice: 3200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/universal-select-heroImg?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Titanium', screwSizes: '1.0, 1.3 mm', plateThickness: '0.25–0.4 mm', applications: 'Frontal, parietal, pediatric', drillBits: 'Single-use carbide' },
    regulatory: { fdaClearance: 'K200234', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400590009', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['CMF', 'micro', 'plating', 'pediatric', 'craniofacial'],
  },
  {
    maId: 'PRD-068', maName: 'SonicWeld Rx Resorbable Fixation',
    maDescription: 'Ultrasonic welding system for resorbable craniomaxillofacial fixation. PDLLA pins are thermally welded into bone, eliminating need for hardware removal.',
    division: 'CMF', category: 'Resorbable Fixation', subcategory: 'Ultrasonic',
    sku: 'STR-SWRX-SYS', price: 15000.00, listPrice: 17500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-Delta?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { technology: 'Ultrasonic welding', material: 'PDLLA (poly-D,L-lactic acid)', pinSizes: '1.6, 2.1 mm', resorption: '12–24 months', applications: 'Cranial, orbital, midface' },
    regulatory: { fdaClearance: 'K210567', deviceClass: 'Class II', productCode: 'HTB', gudid: '00884400590010', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['CMF', 'resorbable', 'ultrasonic', 'fixation', 'PDLLA'],
  },
  {
    maId: 'PRD-069', maName: 'MatrixNEURO Cranial Fixation System',
    maDescription: 'Low-profile cranial flap fixation system with self-drilling screws and titanium clamps. Designed for rapid and reliable craniotomy closure.',
    division: 'CMF', category: 'Cranial Fixation', subcategory: 'Craniotomy',
    sku: 'STR-MXNEURO-SYS', price: 1800.00, listPrice: 2100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-Universal-Neuro?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { components: 'Cranial clamps, plates, screws', screwType: '1.5 mm self-drilling', material: 'Titanium', application: 'Craniotomy flap fixation', profile: 'Ultra-low' },
    regulatory: { fdaClearance: 'K200345', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400590011', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['CMF', 'cranial', 'craniotomy', 'fixation', 'neuro'],
  },
  {
    maId: 'PRD-070', maName: 'CMF Distraction Osteogenesis System',
    maDescription: 'Internal and external distraction devices for gradual bone lengthening in craniofacial applications. Includes mandibular, midface, and cranial vault distractors.',
    division: 'CMF', category: 'Distraction', subcategory: 'Osteogenesis',
    sku: 'STR-CMF-DIST', price: 6500.00, listPrice: 7500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Midface%20Distractor?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { types: 'Internal, external, bidirectional', distractionRange: 'Up to 30 mm', rate: '1 mm/day (adjustable)', material: 'Titanium', applications: 'Mandible, midface, cranial vault' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class II', productCode: 'KWQ', gudid: '00884400590012', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['CMF', 'distraction', 'osteogenesis', 'bone-lengthening'],
  },
  {
    maId: 'PRD-071', maName: 'Medpor Porous Polyethylene Implants',
    maDescription: 'Porous polyethylene implants for facial augmentation and reconstruction. Open pore structure allows tissue ingrowth for long-term implant stability.',
    division: 'CMF', category: 'Facial Reconstruction', subcategory: 'Implants',
    sku: 'STR-MEDPOR', price: 1500.00, listPrice: 1800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-Medpor?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Porous HDPE', poreSize: '100–250 microns', applications: 'Chin, malar, orbital, ear', sterilization: 'Gamma irradiated', carvability: 'Intraoperatively trimmable' },
    regulatory: { fdaClearance: 'K190456', deviceClass: 'Class II', productCode: 'LYZ', gudid: '00884400590013', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['CMF', 'facial', 'implant', 'porous-polyethylene', 'augmentation'],
  },
  {
    maId: 'PRD-072', maName: 'Sternotomy Fixation System',
    maDescription: 'Rigid fixation system for sternal closure after median sternotomy. Titanium plates and screws provide immediate stability and reduce sternal complications.',
    division: 'CMF', category: 'Sternal Fixation', subcategory: 'Closure',
    sku: 'STR-STERN-FIX', price: 2200.00, listPrice: 2500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-SternalPlate?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Titanium', plateTypes: 'Transverse, longitudinal', screwSizes: '2.7, 3.5 mm', lockingOption: 'Self-drilling locking', indication: 'Median sternotomy closure' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400590014', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['CMF', 'sternal', 'fixation', 'sternotomy', 'cardiac'],
  },
  {
    maId: 'PRD-073', maName: 'IsoForm Mandibular Reconstruction Plate',
    maDescription: 'Patient-specific 3D-printed titanium mandibular reconstruction plate designed from CT imaging. Eliminates intraoperative plate bending for oncology and trauma cases.',
    division: 'CMF', category: 'Mandible Fixation', subcategory: 'Custom Reconstruction',
    sku: 'STR-ISO-MAND', price: 9500.00, listPrice: 11000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CMF-product-thumbnail-CranialiD?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { material: '3D-printed titanium', design: 'CT-based patient-specific', screwHoles: 'Pre-planned positions', turnaround: '5–7 business days with VSP', indication: 'Segmental mandibular defect' },
    regulatory: { fdaClearance: 'K220345', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400590015', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 10, minOrderQuantity: 1,
    tags: ['CMF', 'mandible', 'reconstruction', 'patient-specific', '3D-printed'],
  },
];
