// Endoscopy Division — Communications, Endoscopy, ProCare, Sports Medicine
export const endoscopy = [
  {
    maId: 'PRD-074', maName: '1788 AIM 4K Camera Platform',
    maDescription: 'Advanced 4K surgical visualization platform with AIM fluorescence imaging. Provides ultra-high-definition visualization for endoscopic and open procedures.',
    division: 'Endoscopy', category: 'Visualization', subcategory: 'Camera Systems',
    sku: 'STR-1788-4K', price: 85000.00, listPrice: 98000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/1788Tower-BU?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { resolution: '4K Ultra HD', fluorescence: 'AIM (SPY) near-infrared', sensor: 'CMOS 4K', lightSource: 'Integrated LED', display: 'Compatible with 32 in 4K monitor', recording: 'Integrated capture' },
    regulatory: { fdaClearance: 'K210123', deviceClass: 'Class II', productCode: 'GCJ', gudid: '00884400740001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['endoscopy', 'camera', '4K', 'fluorescence', 'visualization'],
  },
  {
    maId: 'PRD-075', maName: 'CrossFire 2 Integrated Arthroscopy',
    maDescription: 'Integrated arthroscopic surgery system combining fluid management, electrosurgery, and tissue management in a single platform. Streamlines OR setup and workflow.',
    division: 'Endoscopy', category: 'Arthroscopy', subcategory: 'Integrated Systems',
    sku: 'STR-CF2-SYS', price: 65000.00, listPrice: 75000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Hero-CrossFire2?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { fluidManagement: 'Automated pressure/flow', electrosurgery: 'Bipolar RF', shaver: 'Integrated power shaver', suction: 'Automated', touchscreen: '15 in display' },
    regulatory: { fdaClearance: 'K210234', deviceClass: 'Class II', productCode: 'GEH', gudid: '00884400740002', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['endoscopy', 'arthroscopy', 'integrated', 'fluid-management'],
  },
  {
    maId: 'PRD-076', maName: 'Formula 180 Arthroscopic Shaver',
    maDescription: 'High-speed arthroscopic shaver handpiece with integrated suction. Lightweight ergonomic design with variable speed control for precision tissue removal.',
    division: 'Endoscopy', category: 'Arthroscopy', subcategory: 'Shavers',
    sku: 'STR-F180-SHAVER', price: 12500.00, listPrice: 14500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/hero-formulashaverhandpieces?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { speed: '0–6,000 RPM', weight: '280 g', suction: 'Integrated through-handpiece', bladeInterface: 'Universal Formula compatible', sterilization: 'Steam autoclavable' },
    regulatory: { fdaClearance: 'K210345', deviceClass: 'Class II', productCode: 'GEH', gudid: '00884400740003', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['endoscopy', 'shaver', 'arthroscopy', 'sports-medicine'],
  },
  {
    maId: 'PRD-077', maName: 'InTouch OR1 Integration System',
    maDescription: 'Operating room integration and communication platform. Routes video, controls devices, and enables telemedicine from a centralized touchscreen interface.',
    division: 'Endoscopy', category: 'Communications', subcategory: 'OR Integration',
    sku: 'STR-OR1-SYS', price: 195000.00, listPrice: 225000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/OR-integration-specialty-hero-v2?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { inputs: '16 HD/4K video inputs', outputs: '8 display outputs', touchscreen: '24 in control panel', routing: 'Seamless video routing', telemedicine: 'Integrated streaming', recording: '4K capture and archiving' },
    regulatory: { fdaClearance: 'K220456', deviceClass: 'Class II', productCode: 'QDQ', gudid: '00884400740004', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 30, minOrderQuantity: 1,
    tags: ['endoscopy', 'communications', 'OR-integration', 'video-routing'],
  },
  {
    maId: 'PRD-078', maName: 'Stryker 32" 4K Surgical Display',
    maDescription: '32-inch medical-grade 4K display for surgical visualization. Designed for OR environments with antimicrobial coating, IP65 rating, and DICOM calibration.',
    division: 'Endoscopy', category: 'Visualization', subcategory: 'Displays',
    sku: 'STR-32-4K-MON', price: 18500.00, listPrice: 21000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Hero-4K?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { size: '32 inches', resolution: '3840 x 2160 (4K UHD)', brightness: '700 cd/m²', colorGamut: '99% sRGB', ipRating: 'IP65 front', calibration: 'DICOM Part 14', coating: 'Antimicrobial' },
    regulatory: { fdaClearance: 'K210456', deviceClass: 'Class I', productCode: 'IYE', gudid: '00884400740005', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['endoscopy', 'display', '4K', 'surgical', 'monitor'],
  },
  {
    maId: 'PRD-079', maName: 'SERFAS Energy RF System',
    maDescription: 'Bipolar radiofrequency energy system for arthroscopic tissue ablation and hemostasis. Temperature-controlled technology limits thermal damage to surrounding tissue.',
    division: 'Endoscopy', category: 'Electrosurgery', subcategory: 'RF Ablation',
    sku: 'STR-SERFAS-RF', price: 28000.00, listPrice: 32000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/HERO-SERFAS?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { technology: 'Bipolar radiofrequency', temperatureControl: 'Yes — thermal management', wands: 'Multiple tip configurations', salineFlow: 'Gravity or pump-assisted', powerRange: '0–45W' },
    regulatory: { fdaClearance: 'K210567', deviceClass: 'Class II', productCode: 'GEH', gudid: '00884400740006', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['endoscopy', 'RF', 'electrosurgery', 'ablation', 'arthroscopy'],
  },
  {
    maId: 'PRD-080', maName: 'ReUnion Shoulder Anchor System',
    maDescription: 'Suture anchor system for arthroscopic and open shoulder repair. Includes knotted and knotless options for rotator cuff, labral, and biceps tenodesis procedures.',
    division: 'Endoscopy', category: 'Sports Medicine', subcategory: 'Shoulder Anchors',
    sku: 'STR-REUN-SHLD', price: 850.00, listPrice: 980.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/ReUnion-RSA-with-shoulder?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { types: 'Knotted, knotless, all-suture', sizes: '2.4–5.5 mm', material: 'PEEK, titanium, all-suture', suture: 'FiberWire and MaxBraid', applications: 'Rotator cuff, labrum, biceps' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class II', productCode: 'HWB', gudid: '00884400740007', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 10,
    tags: ['sports-medicine', 'shoulder', 'suture-anchor', 'rotator-cuff'],
  },
  {
    maId: 'PRD-081', maName: 'CrossFit ACL Reconstruction System',
    maDescription: 'Complete anterior cruciate ligament reconstruction system with femoral and tibial fixation. Includes suspensory and interference screw options for graft fixation.',
    division: 'Endoscopy', category: 'Sports Medicine', subcategory: 'Knee Ligament',
    sku: 'STR-XFIT-ACL', price: 2200.00, listPrice: 2500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/acl-procedural-page-thumb?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { femoralFixation: 'Suspensory button with adjustable loop', tibialFixation: 'Biocomposite interference screw', graftTypes: 'BPTB, hamstring, quadriceps, allograft', drillingSystems: 'Transportal and transtibial', material: 'Titanium button, PLLA/HA screw' },
    regulatory: { fdaClearance: 'K210789', deviceClass: 'Class II', productCode: 'HWB', gudid: '00884400740008', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['sports-medicine', 'ACL', 'knee', 'ligament', 'reconstruction'],
  },
  {
    maId: 'PRD-082', maName: 'Hip Arthroscopy Instrument Set',
    maDescription: 'Comprehensive arthroscopic instrument set for hip procedures including labral repair, femoroacetabular impingement, and capsular management.',
    division: 'Endoscopy', category: 'Sports Medicine', subcategory: 'Hip Arthroscopy',
    sku: 'STR-HIP-ARTH', price: 22000.00, listPrice: 25000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/SM-Hero-R2Hip?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { instruments: 'Cannulas, graspers, suture passers, burrs', scopeAngles: '30° and 70°', scopeDiameter: '4.0 mm', portalOptions: 'Anterolateral, anterior, posterolateral', anchorSystem: 'Dedicated hip anchor' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class I', productCode: 'GEH', gudid: '00884400740009', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['sports-medicine', 'hip', 'arthroscopy', 'labral', 'FAI'],
  },
  {
    maId: 'PRD-083', maName: 'ProCare Premium Service Agreement',
    maDescription: 'Comprehensive equipment service and maintenance agreement for Stryker endoscopic equipment. Includes preventive maintenance, repairs, loaners, and software updates.',
    division: 'Endoscopy', category: 'ProCare', subcategory: 'Service Agreement',
    sku: 'STR-PROCARE-PREM', price: 24000.00, listPrice: 28000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/EndoProCare-Hero-V4?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { coverage: '24/7 phone support', preventiveMaintenance: 'Annual PM included', repairs: 'Unlimited with loaner equipment', parts: 'All parts included', softwareUpdates: 'Included', responseTime: 'Next business day on-site' },
    regulatory: { fdaClearance: 'N/A — Service', deviceClass: 'N/A', productCode: 'N/A', gudid: 'N/A', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 1, minOrderQuantity: 1,
    tags: ['endoscopy', 'ProCare', 'service', 'maintenance', 'agreement'],
  },
  {
    maId: 'PRD-084', maName: 'SPY Fluorescence Imaging Module',
    maDescription: 'Near-infrared fluorescence imaging module for real-time assessment of tissue perfusion. Uses indocyanine green (ICG) to visualize blood flow during surgery.',
    division: 'Endoscopy', category: 'Visualization', subcategory: 'Fluorescence',
    sku: 'STR-SPY-FL', price: 42000.00, listPrice: 48000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Endoscropy-SPY-PHI-thumbnail?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { technology: 'Near-infrared fluorescence (NIR)', dye: 'Indocyanine green (ICG)', wavelength: '805 nm excitation / 830 nm emission', applications: 'Perfusion assessment, lymphatic mapping, biliary visualization', compatibility: '1788 AIM platform' },
    regulatory: { fdaClearance: 'K220567', deviceClass: 'Class II', productCode: 'GCJ', gudid: '00884400740010', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['endoscopy', 'fluorescence', 'SPY', 'ICG', 'perfusion'],
  },
  {
    maId: 'PRD-085', maName: 'Arthroscopic Shaver Blade Kit (50-pack)',
    maDescription: 'Disposable arthroscopic shaver blades in assorted configurations. Includes aggressive, full-radius, and whisker blades for knee, shoulder, and hip procedures.',
    division: 'Endoscopy', category: 'Arthroscopy', subcategory: 'Consumables',
    sku: 'STR-BLADE-50', price: 4500.00, listPrice: 5200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Shavers-Thumb?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { quantity: '50 blades per kit', types: 'Aggressive, full-radius, whisker, abrader', sizes: '3.5, 4.0, 4.5, 5.0 mm', compatibility: 'Formula shaver handpieces', singleUse: 'Yes' },
    regulatory: { fdaClearance: 'K210901', deviceClass: 'Class I', productCode: 'GEH', gudid: '00884400740011', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['endoscopy', 'shaver', 'blades', 'consumable', 'arthroscopy'],
  },
  {
    maId: 'PRD-086', maName: 'Ideal Eyes HD Arthroscopes',
    maDescription: 'High-definition rigid arthroscopes with enhanced optical clarity. Available in 30° and 70° viewing angles for knee, shoulder, hip, and small joint procedures.',
    division: 'Endoscopy', category: 'Arthroscopy', subcategory: 'Scopes',
    sku: 'STR-IE-HD-SCOPE', price: 8500.00, listPrice: 9800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Hero-IdealEyesCmount?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { diameter: '2.7, 4.0 mm', viewingAngles: '0°, 30°, 70°', resolution: 'HD optimized optics', length: '165, 175, 185 mm', sterilization: 'Steam autoclavable', durability: 'Reinforced fiber optic bundle' },
    regulatory: { fdaClearance: 'K210902', deviceClass: 'Class II', productCode: 'GCJ', gudid: '00884400740012', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['endoscopy', 'arthroscope', 'HD', 'optics', 'scope'],
  },
  {
    maId: 'PRD-087', maName: 'Meniscal Repair Device System',
    maDescription: 'All-inside meniscal repair device for arthroscopic treatment of meniscal tears. Pre-loaded implant with curved needle design for posterior horn access.',
    division: 'Endoscopy', category: 'Sports Medicine', subcategory: 'Knee Meniscus',
    sku: 'STR-MENISC-REP', price: 650.00, listPrice: 750.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Air-plus_header1?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { type: 'All-inside implant', implantMaterial: 'PEEK with polyester suture', needleDesign: 'Pre-curved for posterior access', deployment: 'Single-handed', strength: '>80 N pullout' },
    regulatory: { fdaClearance: 'K210903', deviceClass: 'Class II', productCode: 'HWB', gudid: '00884400740013', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 10,
    tags: ['sports-medicine', 'meniscus', 'repair', 'knee', 'all-inside'],
  },
  {
    maId: 'PRD-088', maName: 'WiSe OR Wireless Footswitch',
    maDescription: 'Wireless surgical footswitch for hands-free control of endoscopic equipment. Programmable dual-pedal design with long battery life eliminates cord clutter.',
    division: 'Endoscopy', category: 'Communications', subcategory: 'Accessories',
    sku: 'STR-WISE-FOOT', price: 3200.00, listPrice: 3700.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/CORLite-thumbnail?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { connectivity: 'Wireless RF (2.4 GHz)', pedals: 'Dual programmable', batteryLife: '40+ hours', charging: 'Inductive charging pad', ipRating: 'IPX6 splash-proof', weight: '2.2 lbs' },
    regulatory: { fdaClearance: 'K210904', deviceClass: 'Class I', productCode: 'QDQ', gudid: '00884400740014', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['endoscopy', 'wireless', 'footswitch', 'accessory', 'OR'],
  },
];
