// Healthcare Systems, MedSurg Division
export const healthcareSystems = [
  {
    maId: 'PRD-003', maName: 'Neptune 3 Waste Management System',
    maDescription: 'Integrated surgical waste management system providing continuous suction, smoke evacuation, and fluid disposal. Reduces OR turnover time and improves staff safety.',
    division: 'Healthcare Systems, MedSurg', category: 'OR Equipment', subcategory: 'Waste Management',
    sku: 'STR-NEP3-SYS', price: 42500.00, listPrice: 48000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Neptune3?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { suctionCapacity: '40 liters', noiseLevel: '< 55 dB', powerRequirements: '120V AC, 60Hz', filterType: 'ULPA filtration', weight: '135 lbs' },
    regulatory: { fdaClearance: 'K191876', deviceClass: 'Class II', productCode: 'FRN', gudid: '00884400023456', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['waste-management', 'OR-equipment', 'suction', 'smoke-evacuation'],
  },
  {
    maId: 'PRD-021', maName: 'Neptune 3 Disposable Canister Set (Case of 12)',
    maDescription: 'Disposable fluid collection canisters for Neptune 3 Waste Management System. Pre-connected tubing with integrated solidifier for safe fluid disposal.',
    division: 'Healthcare Systems, MedSurg', category: 'OR Equipment', subcategory: 'Consumables',
    sku: 'STR-NEP3-CAN-12', price: 680.00, listPrice: 780.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/STI84a%20-%20Neptune%20S-165%20copy%20(10)?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { capacity: '3.5 liters per canister', quantity: '12 per case', tubing: 'Pre-attached, 8 ft', solidifier: 'Integrated absorbent polymer', compatibility: 'Neptune 3 only' },
    regulatory: { fdaClearance: 'Exempt', deviceClass: 'Class I', productCode: 'FRN', gudid: '00884400201234', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['consumable', 'neptune', 'canisters', 'waste-management'],
  },
  {
    maId: 'PRD-089', maName: 'Torso Surgical Lighting System',
    maDescription: 'LED surgical overhead light with adjustable color temperature and shadow management. Provides 160,000 lux center illumination with 95+ CRI.',
    division: 'Healthcare Systems, MedSurg', category: 'Surgical Lighting', subcategory: 'Overhead',
    sku: 'STR-TORSO-LIGHT', price: 35000.00, listPrice: 40000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Oculan-web-main-v2?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { illumination: '160,000 lux center', cri: '95+', colorTemperature: '3,500–5,000 K adjustable', lightFieldDiameter: '150–280 mm', technology: 'LED', lifespan: '60,000 hours' },
    regulatory: { fdaClearance: 'K210123', deviceClass: 'Class I', productCode: 'FQC', gudid: '00884400890001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['lighting', 'surgical', 'LED', 'OR-equipment'],
  },
  {
    maId: 'PRD-090', maName: 'Visum LED Headlight System',
    maDescription: 'Wireless surgical LED headlight with lithium-ion battery. Provides focused, shadow-free illumination with adjustable spot size for deep-cavity procedures.',
    division: 'Healthcare Systems, MedSurg', category: 'Surgical Lighting', subcategory: 'Headlights',
    sku: 'STR-VISUM-HL', price: 4800.00, listPrice: 5500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumb-VisumBlade2?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { illumination: '100,000 lux at 30 cm', batteryLife: '6 hours continuous', weight: '198 g (headpiece)', spotSize: 'Adjustable 40–80 mm', wireless: 'Yes — Li-ion battery', charging: '90 minute full charge' },
    regulatory: { fdaClearance: 'K210234', deviceClass: 'Class I', productCode: 'FQC', gudid: '00884400890002', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['lighting', 'headlight', 'wireless', 'LED', 'surgical'],
  },
  {
    maId: 'PRD-091', maName: 'Berchtold Operon D860 Surgical Table',
    maDescription: 'Multi-function surgical table with carbon fiber tabletop for full radiolucency. Supports orthopedic, spine, neuro, and general surgery positioning.',
    division: 'Healthcare Systems, MedSurg', category: 'OR Equipment', subcategory: 'Surgical Tables',
    sku: 'STR-D860-TABLE', price: 85000.00, listPrice: 98000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/d860-update-hero?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weightCapacity: '1,100 lbs', tabletopMaterial: 'Carbon fiber (radiolucent)', length: '80 in', travel: 'Motorized longitudinal slide 12 in', positions: 'Trendelenburg, reverse, lateral, beach chair', compatibility: 'All standard accessories' },
    regulatory: { fdaClearance: 'K220345', deviceClass: 'Class II', productCode: 'FQC', gudid: '00884400890003', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 30, minOrderQuantity: 1,
    tags: ['OR-equipment', 'surgical-table', 'carbon-fiber', 'radiolucent'],
  },
  {
    maId: 'PRD-092', maName: 'SDC Ultra HD Information Management',
    maDescription: 'Surgical documentation and image capture system for recording and managing intraoperative images and video in HD. Integrates with PACS and EMR systems.',
    division: 'Healthcare Systems, MedSurg', category: 'Information Management', subcategory: 'Documentation',
    sku: 'STR-SDC-UHD', price: 32000.00, listPrice: 37000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail-4?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { recording: '4K and HD video capture', storage: 'Integrated 1 TB SSD', connectivity: 'DICOM, HL7, USB, network', emrIntegration: 'Cerner, Epic compatible', streaming: 'Live OR streaming capable' },
    regulatory: { fdaClearance: 'K210456', deviceClass: 'Class I', productCode: 'QDQ', gudid: '00884400890004', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['information-management', 'documentation', 'imaging', 'PACS'],
  },
  {
    maId: 'PRD-093', maName: 'SurgiCount Safety-Sponge System',
    maDescription: 'Barcode-based surgical sponge counting system to prevent retained surgical items. Real-time electronic count verification with audit trail.',
    division: 'Healthcare Systems, MedSurg', category: 'Safety Systems', subcategory: 'Counting',
    sku: 'STR-SURGICOUNT', price: 15000.00, listPrice: 17500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Surgicount%20Tablet_DSC3955b_1-With%20Sponges-URT%20Screen%20NO%20BACKGROUND?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { technology: 'Barcode scanning', scanning: 'Handheld wireless scanner', display: 'Real-time count dashboard', auditTrail: 'Full electronic documentation', emrIntegration: 'Yes', accuracy: '100% barcode read rate' },
    regulatory: { fdaClearance: 'K210567', deviceClass: 'Class I', productCode: 'QBS', gudid: '00884400890005', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['safety', 'sponge-counting', 'retained-items', 'OR-equipment'],
  },
  {
    maId: 'PRD-094', maName: 'Smoke Evacuator Pencil (Box of 25)',
    maDescription: 'Single-use electrosurgical pencil with integrated smoke evacuation. Captures surgical smoke at the source for OR staff safety and visibility.',
    division: 'Healthcare Systems, MedSurg', category: 'Smoke Evacuation', subcategory: 'Consumables',
    sku: 'STR-SMOKE-PEN-25', price: 375.00, listPrice: 440.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Photonblade?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { quantity: '25 per box', type: 'Integrated smoke evacuation pencil', tubing: '10 ft capture tubing', bladeTip: 'Standard and extended', activation: 'Push-button with rocker switch', singleUse: 'Yes' },
    regulatory: { fdaClearance: 'Exempt', deviceClass: 'Class I', productCode: 'GEI', gudid: '00884400890006', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['consumable', 'smoke-evacuation', 'electrosurgery', 'OR-safety'],
  },
  {
    maId: 'PRD-095', maName: 'Pneumatic Tourniquet System',
    maDescription: 'Automated dual-cuff pneumatic tourniquet for limb occlusion during orthopedic and trauma surgery. Features personalized pressure recommendations and automatic cuff detection.',
    division: 'Healthcare Systems, MedSurg', category: 'OR Equipment', subcategory: 'Tourniquets',
    sku: 'STR-TOURN-SYS', price: 8500.00, listPrice: 9800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/smartpump-port?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { cuffs: 'Dual-port, auto-detection', pressureRange: '50–475 mmHg', inflationTime: '< 3 seconds', timers: 'Programmable with alarms', cuffSizes: 'Pediatric through bariatric' },
    regulatory: { fdaClearance: 'K200678', deviceClass: 'Class II', productCode: 'JYQ', gudid: '00884400890007', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['tourniquet', 'OR-equipment', 'pneumatic', 'orthopedic'],
  },
  {
    maId: 'PRD-096', maName: 'FlytePak Sterilization Container',
    maDescription: 'Rigid sterilization container system for instrument set processing. Lightweight aluminum design with tamper-evident locks and RFID tracking compatibility.',
    division: 'Healthcare Systems, MedSurg', category: 'Sterile Processing', subcategory: 'Containers',
    sku: 'STR-FLYTE-CONT', price: 1200.00, listPrice: 1400.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Flyte?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Anodized aluminum', sizes: 'Full, three-quarter, half', filterType: 'Disposable or reusable filter', locks: 'Tamper-evident breakaway', tracking: 'RFID compatible', sterilizationMethods: 'Steam, EtO, STERRAD' },
    regulatory: { fdaClearance: 'K200789', deviceClass: 'Class I', productCode: 'FQC', gudid: '00884400890008', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 10,
    tags: ['sterile-processing', 'container', 'sterilization', 'instrument-management'],
  },
  {
    maId: 'PRD-097', maName: 'IPS Integrated Processing Solution',
    maDescription: 'Automated instrument tracking and workflow management system for sterile processing departments. RFID-based tray tracking with decontamination and assembly guidance.',
    division: 'Healthcare Systems, MedSurg', category: 'Sterile Processing', subcategory: 'Tracking',
    sku: 'STR-IPS-SYS', price: 175000.00, listPrice: 200000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_SterileProcessing?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { technology: 'RFID tray and instrument tracking', modules: 'Decontam, assembly, sterilization, case cart', reporting: 'Dashboard analytics', integration: 'AIMS/EMR compatible', scanners: 'Fixed and handheld RFID' },
    regulatory: { fdaClearance: 'N/A — Software', deviceClass: 'N/A', productCode: 'N/A', gudid: 'N/A', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 60, minOrderQuantity: 1,
    tags: ['sterile-processing', 'IPS', 'RFID', 'tracking', 'workflow'],
  },
  {
    maId: 'PRD-098', maName: 'Patient Warming System',
    maDescription: 'Forced-air patient warming system for perioperative temperature management. Maintains normothermia to reduce surgical site infections and improve outcomes.',
    division: 'Healthcare Systems, MedSurg', category: 'Patient Temperature', subcategory: 'Warming',
    sku: 'STR-WARM-SYS', price: 6500.00, listPrice: 7500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_TemperatureManagement_AC?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { temperature: 'Adjustable 32–43°C', airflow: 'Variable speed', blankets: 'Upper body, lower body, full body', noiseLevel: '< 50 dB', safety: 'Over-temperature shutdown' },
    regulatory: { fdaClearance: 'K200890', deviceClass: 'Class II', productCode: 'KNT', gudid: '00884400890009', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['warming', 'patient-temperature', 'normothermia', 'perioperative'],
  },
  {
    maId: 'PRD-099', maName: 'Surgical Helmet System',
    maDescription: 'Personal protection exhaust system for surgeons. Provides HEPA-filtered air with integrated LED headlight and communication for total joint and revision procedures.',
    division: 'Healthcare Systems, MedSurg', category: 'Personal Protection', subcategory: 'Surgical Helmets',
    sku: 'STR-SURG-HELM', price: 3500.00, listPrice: 4000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/t7-hero?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { filtration: 'HEPA (99.97%)', airflow: 'Continuous positive pressure', headlight: 'Integrated LED', batteryLife: '4 hours', communication: 'Integrated microphone/speaker', weight: '1.6 lbs' },
    regulatory: { fdaClearance: 'K200901', deviceClass: 'Class II', productCode: 'FQC', gudid: '00884400890010', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['personal-protection', 'surgical-helmet', 'HEPA', 'OR-safety'],
  },
];
