// Instruments Division — Interventional Spine, Navigation, Neuro Spine ENT, Surgical
export const instruments = [
  {
    maId: 'PRD-001', maName: 'System 8 Large Bone Power Tool Set',
    maDescription: 'High-performance large bone power tool system featuring oscillating, reciprocating, and sagittal saw attachments. Designed for orthopedic procedures requiring precision cutting.',
    division: 'Instruments', category: 'Surgical Power Tools', subcategory: 'Large Bone',
    sku: 'STR-8000-LB-SET', price: 18750.00, listPrice: 21500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_System8-2?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weight: '2.4 lbs', speed: '0-1200 RPM', powerSource: 'Battery (System 8 SmartLife)', sterilization: 'Steam autoclavable', warranty: '2 years' },
    regulatory: { fdaClearance: 'K201234', deviceClass: 'Class II', productCode: 'HBK', gudid: '00884400012345', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['power-tools', 'large-bone', 'surgical-instruments', 'battery-powered'],
  },
  {
    maId: 'PRD-002', maName: 'System 8 Small Bone Power Tool Set',
    maDescription: 'Compact small bone power tool system for fine orthopedic procedures. Includes micro-oscillating saw, small sagittal saw, and wire driver attachments.',
    division: 'Instruments', category: 'Surgical Power Tools', subcategory: 'Small Bone',
    sku: 'STR-8000-SB-SET', price: 15200.00, listPrice: 17800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_System8CordlessDriverSABO?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weight: '1.6 lbs', speed: '0-1800 RPM', powerSource: 'Battery (System 8 SmartLife)', sterilization: 'Steam autoclavable', warranty: '2 years' },
    regulatory: { fdaClearance: 'K201235', deviceClass: 'Class II', productCode: 'HBK', gudid: '00884400012346', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['power-tools', 'small-bone', 'surgical-instruments', 'battery-powered'],
  },
  {
    maId: 'PRD-010', maName: 'Sonopet iQ Ultrasonic Aspirator',
    maDescription: 'Intelligent ultrasonic aspirator with tissue-selective technology for neurosurgical procedures. Provides precise tissue removal while preserving critical structures.',
    division: 'Instruments', category: 'Neurosurgical Instruments', subcategory: 'Ultrasonic',
    sku: 'STR-SPIQ-SYS', price: 67500.00, listPrice: 75000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/sonopet-iq-console-handpiece?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { frequency: '25 kHz', aspirationRate: 'Variable 0–800 mmHg', handpieceWeight: '250 g', tipOptions: '18 interchangeable tips', display: '10.1 in touchscreen' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class II', productCode: 'GEI', gudid: '00884400090123', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 10, minOrderQuantity: 1,
    tags: ['neurosurgery', 'ultrasonic', 'aspirator', 'tumor-removal'],
  },
  {
    maId: 'PRD-011', maName: 'Target X Surgical Navigation System',
    maDescription: 'Electromagnetic surgical navigation platform for cranial and spinal procedures. Real-time 3D instrument tracking without line-of-sight requirements.',
    division: 'Instruments', category: 'Navigation', subcategory: 'Cranial & Spinal',
    sku: 'STR-TGTX-NAV', price: 285000.00, listPrice: 320000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/tpx-port?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { trackingTechnology: 'Electromagnetic (EM)', accuracy: '< 1.5 mm RMS', display: 'Dual 27 in 4K monitors', imagingCompatibility: 'CT, MRI, O-arm, fluoroscopy' },
    regulatory: { fdaClearance: 'K220123', deviceClass: 'Class II', productCode: 'HBA', gudid: '00884400101234', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 30, minOrderQuantity: 1,
    tags: ['navigation', 'neurosurgery', 'spine', 'electromagnetic'],
  },
  {
    maId: 'PRD-022', maName: 'System 8 SmartLife Battery Pack',
    maDescription: 'High-capacity lithium-ion battery pack for System 8 power tools. SmartLife technology provides real-time charge status and adaptive power management.',
    division: 'Instruments', category: 'Surgical Power Tools', subcategory: 'Accessories',
    sku: 'STR-8000-BATT', price: 2850.00, listPrice: 3200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_System8-1?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { chemistry: 'Lithium-ion', capacity: '3.0 Ah', chargeTime: '75 minutes', runtime: 'Up to 45 min continuous', cycles: '> 500 charge cycles', sterilization: 'Steam autoclavable' },
    regulatory: { fdaClearance: 'K201234', deviceClass: 'Class II', productCode: 'HBK', gudid: '00884400212345', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['battery', 'power-tools', 'system-8', 'accessories'],
  },
  {
    maId: 'PRD-100', maName: 'System 9 Power Tool Platform',
    maDescription: 'Next-generation surgical power tool platform with enhanced torque and speed control. Brushless motor technology extends tool life and reduces maintenance.',
    division: 'Instruments', category: 'Surgical Power Tools', subcategory: 'Next Generation',
    sku: 'STR-9000-PLAT', price: 22500.00, listPrice: 26000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/system9?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { motorType: 'Brushless', speed: '0–2000 RPM', torque: '25% increase over System 8', powerSource: 'System 9 SmartLife battery', weight: '2.1 lbs', sterilization: 'Steam autoclavable' },
    regulatory: { fdaClearance: 'K230123', deviceClass: 'Class II', productCode: 'HBK', gudid: '00884400100001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['power-tools', 'system-9', 'brushless', 'next-generation'],
  },
  {
    maId: 'PRD-101', maName: 'High-Speed Cranial Drill',
    maDescription: 'Electric high-speed drill for cranial access with automatic clutch disengagement. Prevents plunge injury with sensor-based dura detection technology.',
    division: 'Instruments', category: 'Neurosurgical Instruments', subcategory: 'Cranial',
    sku: 'STR-CRAN-DRILL', price: 14500.00, listPrice: 16800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/AriaDrill_hero21?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { speed: '0–75,000 RPM', clutch: 'Auto-disengage (dura detection)', burrs: 'Match-head, cylindrical, diamond', weight: '350 g', powerSource: 'Electric (pneumatic optional)', sterilization: 'Steam autoclavable' },
    regulatory: { fdaClearance: 'K210234', deviceClass: 'Class II', productCode: 'HBK', gudid: '00884400100002', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['neurosurgery', 'cranial', 'drill', 'high-speed', 'instruments'],
  },
  {
    maId: 'PRD-102', maName: 'Q Guidance Spine Navigation',
    maDescription: 'Optical spine navigation system with automated registration. Provides real-time 3D visualization for pedicle screw placement and spinal decompression.',
    division: 'Instruments', category: 'Navigation', subcategory: 'Spine',
    sku: 'STR-QNAV-SPINE', price: 195000.00, listPrice: 225000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Q-Guidance_2022-2?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { trackingTechnology: 'Optical (infrared)', accuracy: '< 1.2 mm', registration: 'Automated surface matching', display: '27 in 4K touchscreen', compatibility: 'O-arm, C-arm, CT' },
    regulatory: { fdaClearance: 'K220234', deviceClass: 'Class II', productCode: 'HBA', gudid: '00884400100003', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 21, minOrderQuantity: 1,
    tags: ['navigation', 'spine', 'optical', 'pedicle-screw', 'image-guided'],
  },
  {
    maId: 'PRD-103', maName: 'Hummer 2 ENT Drill System',
    maDescription: 'Precision ENT surgical drill for otologic and sinus procedures. Ultra-low vibration and whisper-quiet operation for microsurgical applications.',
    division: 'Instruments', category: 'ENT Instruments', subcategory: 'Drills',
    sku: 'STR-HUMMER2-ENT', price: 16500.00, listPrice: 19000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/signature-2-iBur-family-1500x892?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { speed: '0–80,000 RPM', vibration: 'Ultra-low', noiseLevel: '< 55 dB', burrs: 'Diamond, cutting, polishing', irrigation: 'Integrated suction-irrigation', handpieceWeight: '180 g' },
    regulatory: { fdaClearance: 'K210345', deviceClass: 'Class II', productCode: 'HBK', gudid: '00884400100004', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['ENT', 'drill', 'otologic', 'sinus', 'microsurgery'],
  },
  {
    maId: 'PRD-104', maName: 'TPS Micro Drill',
    maDescription: 'Total Performance System micro drill for neurosurgical and ENT applications. Precision micro-motor with foot-pedal speed control for delicate procedures.',
    division: 'Instruments', category: 'Neurosurgical Instruments', subcategory: 'Micro',
    sku: 'STR-TPS-MICRO', price: 11000.00, listPrice: 12800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/pi-drive2?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { speed: '0–100,000 RPM', motor: 'Electric micro-motor', control: 'Foot pedal proportional', attachments: 'Straight, angled, mini', weight: '140 g handpiece' },
    regulatory: { fdaClearance: 'K210456', deviceClass: 'Class II', productCode: 'HBK', gudid: '00884400100005', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['neurosurgery', 'ENT', 'micro-drill', 'precision', 'instruments'],
  },
  {
    maId: 'PRD-105', maName: 'Interventional Spine Cement Delivery System',
    maDescription: 'High-pressure cement delivery system for vertebral augmentation procedures including vertebroplasty and kyphoplasty. Provides controlled, consistent cement delivery.',
    division: 'Instruments', category: 'Interventional Spine', subcategory: 'Cement Delivery',
    sku: 'STR-IS-CEMENT', price: 8500.00, listPrice: 9800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/cement-port?$max_width_720$',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { pressure: 'Up to 400 psi', volume: '10 cc syringe', delivery: 'Hydraulic controlled', cannula: '8–13 gauge options', cement: 'PMMA compatible', visualization: 'Radiopaque for fluoroscopy' },
    regulatory: { fdaClearance: 'K210567', deviceClass: 'Class II', productCode: 'MQP', gudid: '00884400100006', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['interventional-spine', 'cement', 'vertebroplasty', 'kyphoplasty'],
  },
  {
    maId: 'PRD-106', maName: 'Pivot Guard Arthroscopic Instruments',
    maDescription: 'Comprehensive arthroscopic instrument tray for knee and shoulder procedures. Includes punches, graspers, suture passers, and scissors in a modular tray system.',
    division: 'Instruments', category: 'Surgical Instruments', subcategory: 'Arthroscopic',
    sku: 'STR-PIVOT-ARTH', price: 8200.00, listPrice: 9500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/precision-hero-1?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { instruments: 'Punches, graspers, scissors, probes, suture passers', sizes: '2.75, 3.4 mm shaft', applications: 'Knee, shoulder', trayType: 'Modular organized', sterilization: 'Steam autoclavable' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class I', productCode: 'HBY', gudid: '00884400100007', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['instruments', 'arthroscopic', 'knee', 'shoulder', 'surgical'],
  },
  {
    maId: 'PRD-107', maName: 'Precision Multi-Use Sagittal Saw Blade (10-pack)',
    maDescription: 'High-performance sagittal saw blades for System 8 and System 9 handpieces. Precision-ground teeth with proprietary coating for extended cutting life.',
    division: 'Instruments', category: 'Surgical Power Tools', subcategory: 'Consumables',
    sku: 'STR-SAG-BLADE-10', price: 950.00, listPrice: 1100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/cd-nxt-thumb?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { quantity: '10 per pack', types: 'Standard, aggressive, fine', lengths: '50, 70, 90 mm', compatibility: 'System 8 and System 9', material: 'Stainless steel with coating' },
    regulatory: { fdaClearance: 'K201236', deviceClass: 'Class I', productCode: 'HBK', gudid: '00884400100008', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['consumable', 'saw-blade', 'power-tools', 'system-8', 'system-9'],
  },
  {
    maId: 'PRD-108', maName: 'Steri-Shield Drill Guard',
    maDescription: 'Sterile single-use drill guard sleeve for powered surgical instruments. Provides splash protection and maintains sterile field during drilling.',
    division: 'Instruments', category: 'Surgical Power Tools', subcategory: 'Accessories',
    sku: 'STR-SSHIELD-50', price: 450.00, listPrice: 520.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/prd-bg-img-1-2?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { quantity: '50 per box', compatibility: 'Universal — System 8, 9, and competitor', material: 'Clear polycarbonate', singleUse: 'Yes', sterilization: 'EtO pre-sterilized' },
    regulatory: { fdaClearance: 'Exempt', deviceClass: 'Class I', productCode: 'HBK', gudid: '00884400100009', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['consumable', 'drill-guard', 'sterile', 'accessory', 'power-tools'],
  },
  {
    maId: 'PRD-109', maName: 'NAV3i Navigation Platform',
    maDescription: 'Multi-specialty surgical navigation platform supporting cranial, spine, and ENT procedures. Combines optical and electromagnetic tracking with advanced planning software.',
    division: 'Instruments', category: 'Navigation', subcategory: 'Multi-Specialty',
    sku: 'STR-NAV3I', price: 245000.00, listPrice: 280000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/prd-bg-img-1-26-1?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { tracking: 'Optical + electromagnetic hybrid', specialties: 'Cranial, spine, ENT, trauma', display: 'Dual 27 in 4K', planning: 'Advanced 3D trajectory planning', registration: 'Surface, point-pair, and automatic', imaging: 'CT, MRI, O-arm, C-arm' },
    regulatory: { fdaClearance: 'K230234', deviceClass: 'Class II', productCode: 'HBA', gudid: '00884400100010', mdsrCompliant: true },
    availability: 'Made to Order', leadTimeDays: 30, minOrderQuantity: 1,
    tags: ['navigation', 'multi-specialty', 'cranial', 'spine', 'ENT'],
  },
];
