// Medical Division — Patient Care, Patient Handling, EMS
export const medical = [
  {
    maId: 'PRD-004', maName: 'Secure II Hospital Bed',
    maDescription: 'Advanced hospital bed with integrated fall prevention, patient monitoring interface, and caregiver controls. Features intuitive siderail design and powered positioning.',
    division: 'Medical', category: 'Patient Care', subcategory: 'Acute Care Beds',
    sku: 'STR-SEC2-BED', price: 14800.00, listPrice: 16500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/secure-ii-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weightCapacity: '500 lbs', bedWidth: '36 in / 42 in (expandable)', lowHeight: '13.5 in', highHeight: '30 in', siderails: '4-rail split design', powerSupply: '120V AC with battery backup' },
    regulatory: { fdaClearance: 'K200456', deviceClass: 'Class II', productCode: 'FOZ', gudid: '00884400034567', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 10, minOrderQuantity: 1,
    tags: ['hospital-beds', 'acute-care', 'fall-prevention', 'patient-monitoring'],
  },
  {
    maId: 'PRD-005', maName: 'SAGE Prevalon Turn and Position System',
    maDescription: 'Pressure injury prevention system combining continuous lateral rotation therapy with multi-layer microclimate management. Clinically proven to reduce HAIs.',
    division: 'Medical', category: 'Patient Care', subcategory: 'Pressure Management',
    sku: 'STR-SAGE-PTP-200', price: 4250.00, listPrice: 4900.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/sage-prevalon-702x702',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { turnAngle: 'Up to 30 degrees', cycleTime: 'Adjustable 1-4 hours', coverMaterial: 'Low-friction, breathable fabric', weight: '22 lbs', compatibility: 'Standard hospital beds' },
    regulatory: { fdaClearance: 'K180923', deviceClass: 'Class I', productCode: 'KNY', gudid: '00884400045678', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 5,
    tags: ['pressure-injury', 'patient-handling', 'sage', 'prevention'],
  },
  {
    maId: 'PRD-006', maName: 'T5 Prime Powered Stretcher',
    maDescription: 'Electric-powered transport stretcher with fifth-wheel drive system for effortless patient transport. Features integrated scale, Steer-Assist, and retractable head section.',
    division: 'Medical', category: 'Patient Handling', subcategory: 'Stretchers',
    sku: 'STR-T5P-STRETCH', price: 22300.00, listPrice: 25000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/t5-prime-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weightCapacity: '700 lbs', patientSurface: '77 x 28.5 in', batteryLife: '16 miles per charge', integratedScale: 'Yes, ±0.5 lb accuracy', height: '18–37 in', travelSpeed: '3.6 mph max' },
    regulatory: { fdaClearance: 'K210234', deviceClass: 'Class II', productCode: 'FOZ', gudid: '00884400056789', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['stretchers', 'patient-transport', 'powered', 'emergency'],
  },
  {
    maId: 'PRD-007', maName: 'LIFEPAK 15 Monitor/Defibrillator',
    maDescription: 'Professional-grade monitor/defibrillator for advanced life support. Features 12-lead ECG, trending SpO2, EtCO2, and NIBP monitoring with clinical decision support.',
    division: 'Medical', category: 'EMS', subcategory: 'Defibrillators',
    sku: 'STR-LP15-FULL', price: 28900.00, listPrice: 32500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/lifepak15-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { display: '6.5 in color LCD', energyRange: '1–360 joules (biphasic)', ecgLeads: '3, 5, or 12-lead', spo2: 'Masimo SET technology', etco2: 'Microstream sidestream', weight: '18 lbs with battery' },
    regulatory: { fdaClearance: 'K190567', deviceClass: 'Class III', productCode: 'MKJ', gudid: '00884400067890', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['defibrillator', 'emergency', 'ALS', 'monitoring', 'lifepak'],
  },
  {
    maId: 'PRD-110', maName: 'LIFEPAK 20e Defibrillator/Monitor',
    maDescription: 'Hospital-based defibrillator/monitor for emergency departments and critical care. Features synchronized cardioversion, pacing, and code management software.',
    division: 'Medical', category: 'EMS', subcategory: 'Hospital Defibrillators',
    sku: 'STR-LP20E', price: 22500.00, listPrice: 26000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/lifepak20e-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { display: '8.4 in color LCD', energy: '1–360J biphasic', pacing: 'Non-invasive transcutaneous', codeManagement: 'CodeStat data review', connectivity: 'Wi-Fi, USB, Ethernet', weight: '14.5 lbs' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class III', productCode: 'MKJ', gudid: '00884400110001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['defibrillator', 'hospital', 'code-management', 'pacing', 'EMS'],
  },
  {
    maId: 'PRD-111', maName: 'LUCAS 3 Chest Compression System',
    maDescription: 'Mechanical chest compression device for automated CPR. Delivers consistent, guidelines-compliant compressions to improve cardiac arrest outcomes.',
    division: 'Medical', category: 'EMS', subcategory: 'CPR Devices',
    sku: 'STR-LUCAS3', price: 16500.00, listPrice: 19000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/lucas3-702x702',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { compressionRate: '102 ± 2 per minute', compressionDepth: '53 ± 2 mm', batteryRuntime: '45 minutes continuous', weight: '17.6 lbs', patientSize: '17–30.3 cm AP chest', mode: 'Continuous and 30:2' },
    regulatory: { fdaClearance: 'K200123', deviceClass: 'Class III', productCode: 'DRF', gudid: '00884400110002', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['EMS', 'CPR', 'chest-compression', 'cardiac-arrest', 'LUCAS'],
  },
  {
    maId: 'PRD-112', maName: 'Power-PRO 2 Powered Ambulance Cot',
    maDescription: 'Battery-powered ambulance cot with hydraulic lift system. Eliminates manual lifting to reduce EMS provider injuries and improve patient safety.',
    division: 'Medical', category: 'EMS', subcategory: 'Ambulance Cots',
    sku: 'STR-PP2-COT', price: 18500.00, listPrice: 21000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/powerpro2-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weightCapacity: '700 lbs', liftType: 'Battery-powered hydraulic', height: '11.5–35 in', batteryLife: '16 cycles per charge', width: '24 in standard', loadingSystem: 'Power-LOAD compatible' },
    regulatory: { fdaClearance: 'K210234', deviceClass: 'Class II', productCode: 'FOZ', gudid: '00884400110003', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['EMS', 'ambulance-cot', 'powered', 'patient-handling'],
  },
  {
    maId: 'PRD-113', maName: 'Power-LOAD Cot Fastening System',
    maDescription: 'Powered ambulance cot loading/unloading system. Eliminates the need to manually lift the cot during patient loading, reducing back injuries.',
    division: 'Medical', category: 'EMS', subcategory: 'Loading Systems',
    sku: 'STR-PLOAD-SYS', price: 12500.00, listPrice: 14500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/powerload-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { capacity: '700 lbs (cot + patient)', operation: 'Single-operator powered', compatibility: 'Power-PRO 2, Performance-PRO', mountTypes: 'Floor mount, track mount', installTime: '4 hours' },
    regulatory: { fdaClearance: 'K210345', deviceClass: 'Class II', productCode: 'FOZ', gudid: '00884400110004', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['EMS', 'loading-system', 'powered', 'ambulance'],
  },
  {
    maId: 'PRD-114', maName: 'Stair-PRO Stair Chair',
    maDescription: 'Motorized stair descent chair for patient transport on stairs. Powered track system provides controlled, smooth descent without manual lifting.',
    division: 'Medical', category: 'Patient Handling', subcategory: 'Stair Chairs',
    sku: 'STR-STAIRPRO', price: 5800.00, listPrice: 6700.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/stairpro-702x702',
    isConfigurable: false, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weightCapacity: '500 lbs', descentMethod: 'Powered track', speed: 'Variable, operator-controlled', batteryLife: '20+ flights per charge', weight: '52 lbs', foldable: 'Yes — compact storage' },
    regulatory: { fdaClearance: 'K210456', deviceClass: 'Class II', productCode: 'FOZ', gudid: '00884400110005', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['patient-handling', 'stair-chair', 'powered', 'EMS'],
  },
  {
    maId: 'PRD-115', maName: 'ProCuity Med-Surg Bed',
    maDescription: 'Intelligent medical-surgical bed with integrated patient monitoring, early mobility features, and iBed Awareness technology for caregiver notifications.',
    division: 'Medical', category: 'Patient Care', subcategory: 'Med-Surg Beds',
    sku: 'STR-PROCUITY', price: 18500.00, listPrice: 21000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/procuity-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weightCapacity: '500 lbs', iBed: 'Awareness notification system', earlyMobility: 'Integrated chair position', lowHeight: '12.5 in', scale: 'Integrated weighing', communication: 'Nurse call integration' },
    regulatory: { fdaClearance: 'K220456', deviceClass: 'Class II', productCode: 'FOZ', gudid: '00884400110006', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['hospital-beds', 'med-surg', 'iBed', 'smart-bed', 'patient-care'],
  },
  {
    maId: 'PRD-116', maName: 'IsoFlex SE Mattress',
    maDescription: 'Multi-zone pressure redistribution mattress for acute care beds. Viscoelastic foam with IsoFlex zones provides targeted support for pressure injury prevention.',
    division: 'Medical', category: 'Patient Care', subcategory: 'Mattresses',
    sku: 'STR-ISOFLEX-SE', price: 1800.00, listPrice: 2100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/isoflex-702x702',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Multi-density viscoelastic foam', zones: '3-zone pressure redistribution', cover: 'Fluid-resistant, antimicrobial', weightCapacity: '500 lbs', dimensions: '80 x 36 x 6 in', compatibility: 'Secure II, ProCuity beds' },
    regulatory: { fdaClearance: 'K200567', deviceClass: 'Class I', productCode: 'KNT', gudid: '00884400110007', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['mattress', 'pressure-redistribution', 'foam', 'patient-care'],
  },
  {
    maId: 'PRD-117', maName: 'SAGE CHG Bathing Cloths (Case of 60)',
    maDescription: 'Pre-moistened 2% chlorhexidine gluconate (CHG) bathing cloths for patient decolonization. Clinically proven to reduce healthcare-associated infections.',
    division: 'Medical', category: 'Patient Care', subcategory: 'Skin Antisepsis',
    sku: 'STR-SAGE-CHG-60', price: 850.00, listPrice: 980.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/sage-chg-702x702',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { activeIngredient: '2% CHG', quantity: '60 packs per case (6 cloths/pack)', size: '7.5 x 7.5 in cloths', fragrance: 'Fragrance-free', latex: 'Latex-free', warming: 'Microwave safe' },
    regulatory: { fdaClearance: 'K190234', deviceClass: 'Class II (OTC drug)', productCode: 'KGO', gudid: '00884400110008', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['consumable', 'CHG', 'bathing', 'infection-prevention', 'SAGE'],
  },
  {
    maId: 'PRD-118', maName: 'PHYSIO-CONTROL LIFENET System',
    maDescription: 'Cloud-based data management platform for EMS agencies. Enables real-time patient data transmission, device fleet management, and quality improvement analytics.',
    division: 'Medical', category: 'EMS', subcategory: 'Data Management',
    sku: 'STR-LIFENET', price: 45000.00, listPrice: 52000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/lifenet-702x702',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { dataTransmission: 'Real-time 12-lead ECG to hospital', fleetManagement: 'Remote device monitoring', analytics: 'CPR quality, response time', cloudBased: 'Yes — secure HIPAA compliant', compatibility: 'LIFEPAK 15, 20e, CR2' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class II', productCode: 'MKJ', gudid: '00884400110009', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['EMS', 'data-management', 'LIFENET', 'cloud', 'analytics'],
  },
  {
    maId: 'PRD-119', maName: 'S3 MedSurg Bed',
    maDescription: 'Standard medical-surgical bed with essential fall prevention features. GoBed position for safe patient egress and nurse controls for efficient care delivery.',
    division: 'Medical', category: 'Patient Care', subcategory: 'Med-Surg Beds',
    sku: 'STR-S3-BED', price: 9500.00, listPrice: 11000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/s3-bed-702x702',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { weightCapacity: '500 lbs', lowHeight: '15 in', siderails: 'Split, quarter-length', goBed: 'One-button safe egress position', brakes: 'Central brake with indicator', width: '35 in standard' },
    regulatory: { fdaClearance: 'K200678', deviceClass: 'Class II', productCode: 'FOZ', gudid: '00884400110010', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 10, minOrderQuantity: 1,
    tags: ['hospital-beds', 'med-surg', 'fall-prevention', 'patient-care'],
  },
  {
    maId: 'PRD-120', maName: 'Big Wheel Transport Chair',
    maDescription: 'Oversized wheel transport wheelchair for safe patient movement. Low seat height and padded armrests improve patient comfort during inter-department transfers.',
    division: 'Medical', category: 'Patient Handling', subcategory: 'Transport',
    sku: 'STR-BIGWHEEL', price: 1200.00, listPrice: 1400.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/bigwheel-702x702',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { weightCapacity: '500 lbs', seatWidth: '22 in', wheelSize: '12 in rear, 8 in front', armrests: 'Padded flip-up', footrests: 'Swing-away', weight: '38 lbs' },
    regulatory: { fdaClearance: 'K190345', deviceClass: 'Class I', productCode: 'FOZ', gudid: '00884400110011', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['patient-handling', 'transport', 'wheelchair', 'mobility'],
  },
];
