// Neurovascular Division
export const neurovascular = [
  {
    maId: 'PRD-012', maName: 'Neuro Matrix Programmable Shunt System',
    maDescription: 'Programmable CSF shunt valve with integrated anti-siphon device. Externally adjustable pressure settings allow non-invasive hydrocephalus management.',
    division: 'Neurovascular', category: 'Neuro Implants', subcategory: 'Hydrocephalus',
    sku: 'STR-NMTX-SHUNT', price: 3200.00, listPrice: 3800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/neuroform-atlas-hero-graphic?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { pressureSettings: '18 settings (30–200 mmH2O)', adjustmentMethod: 'External magnetic programmer', material: 'Titanium, silicone', mriCompatibility: 'MR Conditional (1.5T and 3T)', antiSiphon: 'Integrated gravitational device' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class II', productCode: 'LYA', gudid: '00884400112345', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['hydrocephalus', 'shunt', 'programmable', 'csf', 'neuro-implant'],
  },
  {
    maId: 'PRD-013', maName: 'Surpass Evolve Flow Diverter',
    maDescription: 'Intracranial flow diverter for endovascular treatment of wide-neck, large, and giant intracranial aneurysms. Enhanced deliverability and precise deployment.',
    division: 'Neurovascular', category: 'Flow Diversion', subcategory: 'Aneurysm Treatment',
    sku: 'STR-SRPS-EVLV', price: 12500.00, listPrice: 14200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Surpass_Image_1?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Cobalt-chromium alloy', diameterRange: '2.5–5.5 mm', lengthRange: '12–40 mm', deliveryCatheter: '0.040 in ID microcatheter', porosity: '55–70%', meshDensity: '48 wires' },
    regulatory: { fdaClearance: 'P200045 (PMA)', deviceClass: 'Class III', productCode: 'QBG', gudid: '00884400123456', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['neurovascular', 'flow-diverter', 'aneurysm', 'endovascular'],
  },
  {
    maId: 'PRD-121', maName: 'Trevo XP ProVue Retriever',
    maDescription: 'Stent retriever for mechanical thrombectomy in acute ischemic stroke. Fully visible under fluoroscopy with optimized radial force for thrombus integration.',
    division: 'Neurovascular', category: 'Stroke Treatment', subcategory: 'Thrombectomy',
    sku: 'STR-TREVO-XP', price: 8500.00, listPrice: 9800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Trevo-XP?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { sizes: '3x20, 4x20, 4x30, 6x25 mm', material: 'Nitinol with platinum markers', visibility: 'Full-length radiopacity', pushWire: '0.018 in', compatibility: 'AXS Catalyst and Vecta catheters' },
    regulatory: { fdaClearance: 'K220123', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['neurovascular', 'thrombectomy', 'stroke', 'retriever', 'trevo'],
  },
  {
    maId: 'PRD-122', maName: 'AXS Catalyst 7 Distal Access Catheter',
    maDescription: 'Large-bore distal access catheter for neurovascular interventions. Provides stable intracranial platform for thrombectomy and coiling procedures.',
    division: 'Neurovascular', category: 'Access Catheters', subcategory: 'Distal Access',
    sku: 'STR-AXS-CAT7', price: 2800.00, listPrice: 3200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/AXS-Catalyst-7?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { innerDiameter: '0.072 in', outerDiameter: '7 Fr', lengths: '115, 125, 132 cm', tipDesign: 'Atraumatic distal tip', coating: 'Hydrophilic distal, hydrophobic proximal' },
    regulatory: { fdaClearance: 'K220234', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210002', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 5,
    tags: ['neurovascular', 'catheter', 'distal-access', 'thrombectomy'],
  },
  {
    maId: 'PRD-123', maName: 'AXS Vecta 71 Aspiration Catheter',
    maDescription: 'Large-bore aspiration catheter for direct aspiration thrombectomy technique (ADAPT). Maximized inner lumen for efficient thrombus aspiration.',
    division: 'Neurovascular', category: 'Access Catheters', subcategory: 'Aspiration',
    sku: 'STR-AXS-VECTA', price: 2400.00, listPrice: 2800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Vecta_Hero?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { innerDiameter: '0.071 in', outerDiameter: '6.7 Fr', lengths: '125, 132 cm', aspiration: 'Optimized for ADAPT technique', compatibility: 'AXS Universal platform' },
    regulatory: { fdaClearance: 'K220345', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210003', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 5,
    tags: ['neurovascular', 'aspiration', 'catheter', 'thrombectomy', 'ADAPT'],
  },
  {
    maId: 'PRD-124', maName: 'Target XL Detachable Coils',
    maDescription: 'Platinum detachable embolization coils for intracranial aneurysm treatment. Available in framing, filling, and finishing configurations for complete aneurysm occlusion.',
    division: 'Neurovascular', category: 'Embolization', subcategory: 'Coils',
    sku: 'STR-TARGET-XL', price: 3200.00, listPrice: 3700.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Target-Coil-Hel%20copy?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Platinum/tungsten alloy', types: 'Standard, Nano, Soft', diameters: '2–20 mm', lengths: '2–60 cm', detachment: 'Instant electrolytic', deliveryWire: '0.014 in' },
    regulatory: { fdaClearance: 'K220456', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210004', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['neurovascular', 'coils', 'embolization', 'aneurysm', 'platinum'],
  },
  {
    maId: 'PRD-125', maName: 'Excelsior SL-10 Microcatheter',
    maDescription: 'Pre-shaped microcatheter for intracranial navigation and coil delivery. Steam-shapeable distal tip allows customized access to complex neurovascular anatomy.',
    division: 'Neurovascular', category: 'Microcatheters', subcategory: 'Delivery',
    sku: 'STR-SL10-MICRO', price: 1200.00, listPrice: 1400.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Excelsior-SL-10?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { innerDiameter: '0.017 in', outerDiameter: '2.6 Fr distal', length: '150 cm', tipShapes: 'Straight, 45°, 90°, S-curve, custom', coating: 'Hydrophilic', compatibility: 'Target and Barricade coils' },
    regulatory: { fdaClearance: 'K210567', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210005', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 5,
    tags: ['neurovascular', 'microcatheter', 'coil-delivery', 'intracranial'],
  },
  {
    maId: 'PRD-126', maName: 'Neuroform Atlas Stent',
    maDescription: 'Self-expanding intracranial stent for stent-assisted coiling of wide-neck bifurcation aneurysms. Open-cell design allows coil delivery through stent interstices.',
    division: 'Neurovascular', category: 'Neurovascular Stents', subcategory: 'Intracranial',
    sku: 'STR-NFORM-ATLAS', price: 6500.00, listPrice: 7500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/neuroform-atlas-hero-graphic?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Nitinol', diameters: '2.5–4.5 mm', lengths: '15–30 mm', cellDesign: 'Open-cell', delivery: 'Over-the-wire (0.017 in)', visibility: 'Radiopaque markers' },
    regulatory: { fdaClearance: 'P170024 (PMA)', deviceClass: 'Class III', productCode: 'QBG', gudid: '00884400210006', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['neurovascular', 'stent', 'intracranial', 'aneurysm', 'coiling'],
  },
  {
    maId: 'PRD-127', maName: 'Synchro 2 Microguidewire',
    maDescription: 'Neurovascular microguidewire for intracranial catheter navigation. Soft atraumatic tip with responsive torque transmission for precise vessel selection.',
    division: 'Neurovascular', category: 'Guidewires', subcategory: 'Microguidewires',
    sku: 'STR-SYNCH2-WIRE', price: 450.00, listPrice: 520.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Synchro?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { diameter: '0.014 in', length: '200, 300 cm', tipLoad: 'Standard and soft', coating: 'Hydrophilic', coreMaterial: 'Nitinol', tipShapeable: 'Yes — steam' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210007', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 10,
    tags: ['neurovascular', 'guidewire', 'microguidewire', 'intracranial'],
  },
  {
    maId: 'PRD-128', maName: 'Surpass Streamline Flow Diverter',
    maDescription: 'Second-generation flow diverter for intracranial aneurysms with enhanced trackability. Woven mesh design promotes endothelialization for aneurysm exclusion.',
    division: 'Neurovascular', category: 'Flow Diversion', subcategory: 'Aneurysm Treatment',
    sku: 'STR-SRPS-STRM', price: 11000.00, listPrice: 12800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Surpass-Streamline?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'CoCr alloy', diameters: '3.0–5.0 mm', lengths: '15–50 mm', delivery: '0.040 in ID catheter', wires: '48 wires', resheathing: 'Fully resheathe up to 80%' },
    regulatory: { fdaClearance: 'P200046 (PMA)', deviceClass: 'Class III', productCode: 'QBG', gudid: '00884400210008', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['neurovascular', 'flow-diverter', 'aneurysm', 'endovascular'],
  },
  {
    maId: 'PRD-129', maName: 'AXS Infinity LS Guide Catheter',
    maDescription: 'Long-sheath guide catheter for neurovascular access. Optimized flexibility and support for intracranial intervention from femoral or radial approach.',
    division: 'Neurovascular', category: 'Access Catheters', subcategory: 'Guide Catheters',
    sku: 'STR-AXS-INF-LS', price: 1800.00, listPrice: 2100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/AXS-Infinity-LS?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { innerDiameter: '0.088 in', outerDiameter: '8 Fr', lengths: '80, 90, 95 cm', construction: 'Braided with PTFE liner', compatibility: 'AXS Universal platform' },
    regulatory: { fdaClearance: 'K220567', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210009', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 5,
    tags: ['neurovascular', 'guide-catheter', 'access', 'intracranial'],
  },
  {
    maId: 'PRD-130', maName: 'Barricade Coil System',
    maDescription: 'Detachable embolization coils with hydrogel expansion technology for enhanced aneurysm fill. Hydrogel coating expands after deployment for improved packing density.',
    division: 'Neurovascular', category: 'Embolization', subcategory: 'Hydrogel Coils',
    sku: 'STR-BARRICADE', price: 4500.00, listPrice: 5200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/embolization?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Platinum with hydrogel', expansion: '5–7x volume increase', activationTime: '20 minutes', sizes: '2–20 mm diameter', types: 'Framing, filling, finishing', detachment: 'Electrolytic' },
    regulatory: { fdaClearance: 'K220678', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210010', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 1,
    tags: ['neurovascular', 'coils', 'hydrogel', 'embolization', 'aneurysm'],
  },
  {
    maId: 'PRD-131', maName: 'NV Stroke Procedure Kit',
    maDescription: 'Pre-packaged procedure kit containing essential neurovascular devices for mechanical thrombectomy in acute ischemic stroke. Reduces case preparation time.',
    division: 'Neurovascular', category: 'Stroke Treatment', subcategory: 'Procedure Kits',
    sku: 'STR-NV-STROKE-KIT', price: 15000.00, listPrice: 17500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/AXS-Universal?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { contents: 'Guide catheter, aspiration catheter, microcatheter, microguidewire, retriever', casePrepTime: 'Reduced 50%', singleUse: 'Yes', packaging: 'Sterile, organized by sequence' },
    regulatory: { fdaClearance: 'K220789', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210011', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 5,
    tags: ['neurovascular', 'stroke', 'procedure-kit', 'thrombectomy', 'bundle'],
  },
  {
    maId: 'PRD-132', maName: 'Cerebral Angiography Catheter Set',
    maDescription: 'Diagnostic cerebral angiography catheter set for neurovascular imaging. Includes pre-shaped catheters for selective catheterization of cerebral vessels.',
    division: 'Neurovascular', category: 'Diagnostic', subcategory: 'Angiography',
    sku: 'STR-CEREB-ANGIO', price: 350.00, listPrice: 420.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/thrombectomy?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { catheters: 'Simmons 2, Vertebral, JB1, JB2', size: '5 Fr', length: '100, 110, 125 cm', material: 'Nylon with hydrophilic coating', singleUse: 'Yes' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class II', productCode: 'QBG', gudid: '00884400210012', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 2, minOrderQuantity: 10,
    tags: ['neurovascular', 'diagnostic', 'angiography', 'catheter', 'cerebral'],
  },
  {
    maId: 'PRD-133', maName: 'WEB Aneurysm Embolization System',
    maDescription: 'Intrasaccular flow disruption device for treatment of wide-neck bifurcation aneurysms. Single-device treatment without need for adjunctive stenting.',
    division: 'Neurovascular', category: 'Embolization', subcategory: 'Intrasaccular',
    sku: 'STR-WEB-SYS', price: 9500.00, listPrice: 11000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/stk%20antman%2007%2003%2001hr?$max_width_720$',
    isConfigurable: true, isSerialManaged: true, isBatchManaged: true, isSubscriptionEligible: false,
    specifications: { material: 'Nitinol braided', sizes: '3x2 to 11x9 mm', delivery: 'VIA microcatheter (0.027 in)', resheathing: 'Fully retrievable before detach', design: 'Single-layer and dual-layer', antiplatelet: 'Not required (single-device)' },
    regulatory: { fdaClearance: 'P200047 (PMA)', deviceClass: 'Class III', productCode: 'QBG', gudid: '00884400210013', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['neurovascular', 'WEB', 'intrasaccular', 'aneurysm', 'embolization'],
  },
];
