// Reconstructive Division — Hips, Knees, Robotics
export const reconstructive = [
  {
    maId: 'PRD-008',
    maName: 'Trident II Acetabular System',
    maDescription: 'Modular acetabular system with tritanium 3D-printed shell for enhanced biologic fixation. Offers multiple bearing options and an intuitive locking mechanism for reliable intraoperative assembly.',
    division: 'Reconstructive',
    category: 'Hip Replacement',
    subcategory: 'Acetabular',
    sku: 'STR-TRD2-ACET',
    price: 6800.00,
    listPrice: 7900.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/JR_Hip_TridentII_01_Hero_Image?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { shellSizes: '44–72 mm (2 mm increments)', material: 'Tritanium 3D-printed titanium', bearingSurfaces: 'Ceramic, Polyethylene, X3 HXLPE', linerOptions: 'Neutral, 10°, 20° lip', screwHoles: 'Multi-hole and cluster hole options', coating: 'Hydroxyapatite (HA)' },
    regulatory: { fdaClearance: 'K200789', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400078901', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['hip', 'acetabular', 'joint-replacement', 'tritanium', '3d-printed'],
  },
  {
    maId: 'PRD-014',
    maName: 'Mako SmartRobotics System',
    maDescription: 'Robotic-arm assisted surgical platform for total knee, total hip, and partial knee arthroplasty. CT-based 3D planning with intraoperative haptic guidance enables reproducible bone preparation.',
    division: 'Reconstructive',
    category: 'Robotic Surgery',
    subcategory: 'Joint Replacement',
    sku: 'STR-MAKO-SYS-4',
    price: 1250000.00,
    listPrice: 1450000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Mako%204%20Family%204%204K%20with%20shadow3?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: true,
    specifications: { applications: 'TKA, THA, PKA', armType: '6-DOF robotic arm', planning: 'CT-based 3D preoperative planning', guidance: 'AccuStop haptic technology', display: '3x 27 in surgical displays', weight: '800 lbs', softwarePlatform: 'Mako BluePrint 4.0' },
    regulatory: { fdaClearance: 'K211045', deviceClass: 'Class II', productCode: 'OWJ', gudid: '00884400134567', mdsrCompliant: true },
    availability: 'Made to Order',
    leadTimeDays: 60,
    minOrderQuantity: 1,
    tags: ['robotics', 'mako', 'joint-replacement', 'TKA', 'THA', 'surgical-robot'],
  },
  {
    maId: 'PRD-015',
    maName: 'Triathlon Total Knee System',
    maDescription: 'Comprehensive total knee replacement system with anatomic design derived from shape-matching technology. Single-radius design provides natural stability and improved quadriceps efficiency.',
    division: 'Reconstructive',
    category: 'Knee Replacement',
    subcategory: 'Total Knee',
    sku: 'STR-TRI-TKS',
    price: 8500.00,
    listPrice: 9800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Hero_JR_Knee_Triathlon_Primary?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { femoralSizes: '1–8 (with +/- sizes)', tibialSizes: '1–9', bearingOptions: 'CR, PS, CS, AS', material: 'CoCr femoral, Ti tibial, X3 HXLPE insert', fixation: 'Cemented or cementless (tritanium)', compatibility: 'Mako robotic-arm compatible' },
    regulatory: { fdaClearance: 'K201567', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400145678', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    tags: ['knee', 'total-knee', 'joint-replacement', 'triathlon', 'mako-compatible'],
  },
  {
    maId: 'PRD-016',
    maName: 'Accolade II Femoral Hip Stem',
    maDescription: 'Morphometric tapered-wedge femoral stem utilizing PureFit technology for reliable metaphyseal fixation. Designed to match proximal femoral anatomy with a shortened, tapered distal geometry.',
    division: 'Reconstructive',
    category: 'Hip Replacement',
    subcategory: 'Femoral Stems',
    sku: 'STR-ACC2-STEM',
    price: 5200.00,
    listPrice: 6100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Hero_JR_Hip_AccoladeII?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { stemSizes: '0–8 (standard & lateralized)', material: 'TMZF alloy (Ti-12Mo-6Zr-2Fe)', coating: 'PureFit HA plasma spray (proximal)', neckOptions: 'Standard and high offset', headSizes: '22.2, 28, 32, 36, 40 mm', taper: '12/14 V40' },
    regulatory: { fdaClearance: 'K190234', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400156789', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    tags: ['hip', 'femoral-stem', 'joint-replacement', 'cementless', 'mako-compatible'],
  },
  {
    maId: 'PRD-020',
    maName: 'Tornier Perform Reversed Shoulder System',
    maDescription: 'Reverse total shoulder arthroplasty system for rotator cuff deficient shoulders. Medialized glenosphere design with lateralized humerus provides optimized biomechanics.',
    division: 'Reconstructive',
    category: 'Shoulder Replacement',
    subcategory: 'Reverse Shoulder',
    sku: 'STR-TOR-RSA',
    price: 9200.00,
    listPrice: 10800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/TornierPerformReversed?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { glenosphereSizes: '36, 39, 42 mm', baseplateType: 'Press-fit with peripheral screws', humeral: 'Modular stem (5 sizes)', material: 'CoCr glenosphere, Ti baseplate, HXLPE liner', bearingOptions: 'Standard, retentive', convertibility: 'Anatomic to reverse conversion capable' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400190123', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['shoulder', 'reverse-shoulder', 'joint-replacement', 'rotator-cuff'],
  },
  {
    maId: 'PRD-023',
    maName: 'Mako Total Hip Application',
    maDescription: 'Software and instrument application for Mako robotic-arm assisted total hip arthroplasty. Enables CT-based 3D planning for acetabular cup and femoral stem placement.',
    division: 'Reconstructive',
    category: 'Robotic Surgery',
    subcategory: 'Applications',
    sku: 'STR-MAKO-THA-APP',
    price: 185000.00,
    listPrice: 210000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Mako%204%20THA%202K?$max_width_720$',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: true,
    specifications: { platform: 'Mako SmartRobotics', planning: '3D CT-based', procedure: 'Total Hip Arthroplasty', compatibility: 'Trident II, Accolade II' },
    regulatory: { fdaClearance: 'K211046', deviceClass: 'Class II', productCode: 'OWJ', gudid: '00884400230001', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 14,
    minOrderQuantity: 1,
    tags: ['mako', 'robotics', 'THA', 'hip', 'software'],
  },
  {
    maId: 'PRD-024',
    maName: 'Mako Partial Knee Application',
    maDescription: 'Software and instrument application for Mako robotic-arm assisted partial knee arthroplasty. Provides real-time intraoperative adjustments for optimal implant positioning.',
    division: 'Reconstructive',
    category: 'Robotic Surgery',
    subcategory: 'Applications',
    sku: 'STR-MAKO-PKA-APP',
    price: 165000.00,
    listPrice: 190000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/PKA%20Hero?$max_width_720$',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: true,
    specifications: { platform: 'Mako SmartRobotics', planning: '3D CT-based', procedure: 'Partial Knee Arthroplasty', compatibility: 'Restoris MCK' },
    regulatory: { fdaClearance: 'K211047', deviceClass: 'Class II', productCode: 'OWJ', gudid: '00884400230002', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 14,
    minOrderQuantity: 1,
    tags: ['mako', 'robotics', 'PKA', 'knee', 'software'],
  },
  {
    maId: 'PRD-025',
    maName: 'Tritanium Primary Acetabular Shell',
    maDescription: 'Highly porous 3D-printed titanium acetabular shell designed for biologic fixation. Pore structure mimics cancellous bone architecture for enhanced osseointegration.',
    division: 'Reconstructive',
    category: 'Hip Replacement',
    subcategory: 'Acetabular',
    sku: 'STR-TRIT-PRI-SHELL',
    price: 4200.00,
    listPrice: 4900.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/JR_Hip_TridentII_01_Hero_Image?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { shellSizes: '44–66 mm', porosity: '~60%', poreSize: '100–700 microns', material: 'Tritanium Ti alloy', fixation: 'Press-fit with optional screw augmentation' },
    regulatory: { fdaClearance: 'K200790', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400230003', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['hip', 'acetabular', 'tritanium', '3d-printed', 'cementless'],
  },
  {
    maId: 'PRD-026',
    maName: 'Triathlon Tritanium Cementless Baseplate',
    maDescription: 'Cementless tibial baseplate featuring 3D-printed Tritanium technology for biologic fixation in total knee arthroplasty. Designed for use with the Triathlon Knee System.',
    division: 'Reconstructive',
    category: 'Knee Replacement',
    subcategory: 'Total Knee',
    sku: 'STR-TRI-TRIT-BASE',
    price: 3800.00,
    listPrice: 4400.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/JR-Knee-Triathlon-Cementless-Hero-image03?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { sizes: '1–9', material: 'Tritanium 3D-printed Ti', fixation: 'Cementless press-fit', compatibility: 'Triathlon Total Knee System', bearing: 'X3 HXLPE' },
    regulatory: { fdaClearance: 'K210234', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400230004', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['knee', 'cementless', 'tritanium', 'baseplate', 'triathlon'],
  },
  {
    maId: 'PRD-027',
    maName: 'X3 Advanced Bearing Insert',
    maDescription: 'Highly crosslinked polyethylene bearing insert with sequential irradiation and annealing process. Provides superior oxidative stability and wear resistance for hip and knee arthroplasty.',
    division: 'Reconstructive',
    category: 'Bearings',
    subcategory: 'Polyethylene',
    sku: 'STR-X3-INSERT',
    price: 1800.00,
    listPrice: 2100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_X3?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'X3 HXLPE (sequentially crosslinked)', wearRate: '<0.005 mm/year', oxidationIndex: '< 1.0', sterilization: 'Gamma irradiation in nitrogen', sizes: 'Multiple for hip and knee' },
    regulatory: { fdaClearance: 'K190567', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400230005', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    tags: ['bearing', 'polyethylene', 'X3', 'hip', 'knee', 'wear-resistant'],
  },
  {
    maId: 'PRD-028',
    maName: 'LFIT Anatomic CoCr Femoral Head',
    maDescription: 'Cobalt-chromium femoral head with precision-machined surface finish for total hip arthroplasty. Available in multiple diameters for optimal range of motion and stability.',
    division: 'Reconstructive',
    category: 'Hip Replacement',
    subcategory: 'Femoral Heads',
    sku: 'STR-LFIT-HEAD',
    price: 1200.00,
    listPrice: 1400.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Hero_JR_Hip_AccoladeII?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'CoCr alloy', diameters: '22.2, 28, 32, 36, 40 mm', taper: '12/14 V40', neckLengths: '-3.5 to +10.5 mm', surfaceFinish: 'Mirror polished' },
    regulatory: { fdaClearance: 'K190568', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400230006', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    tags: ['hip', 'femoral-head', 'CoCr', 'joint-replacement'],
  },
  {
    maId: 'PRD-029',
    maName: 'Tornier Perform Anatomic Shoulder System',
    maDescription: 'Anatomic total shoulder arthroplasty system with comprehensive sizing options. Modular humeral design allows intraoperative flexibility and potential conversion to reverse shoulder.',
    division: 'Reconstructive',
    category: 'Shoulder Replacement',
    subcategory: 'Anatomic Shoulder',
    sku: 'STR-TOR-ANAT',
    price: 8500.00,
    listPrice: 9800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Perform_Humeral_System_Hero-Product-Image_666x392?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { glenoidType: 'Keeled and pegged', humeralSizes: '5 stem sizes', headSizes: '40–54 mm', material: 'CoCr head, UHMWPE glenoid, Ti stem', convertibility: 'Convertible to reverse' },
    regulatory: { fdaClearance: 'K210679', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400230007', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['shoulder', 'anatomic', 'total-shoulder', 'joint-replacement'],
  },
  {
    maId: 'PRD-030',
    maName: 'Restoris MCK Partial Knee Implant',
    maDescription: 'Medial compartment knee implant designed for robotic-arm assisted unicompartmental knee arthroplasty with the Mako system. Preserves healthy bone and ligaments.',
    division: 'Reconstructive',
    category: 'Knee Replacement',
    subcategory: 'Partial Knee',
    sku: 'STR-RMCK-PKA',
    price: 6200.00,
    listPrice: 7200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/MCK_BiC_Onlay?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { compartments: 'Medial, Lateral', femoralSizes: '6 sizes', tibialSizes: '6 sizes', material: 'CoCr femoral, Ti tibial, UHMWPE insert', fixation: 'Cemented', compatibility: 'Mako robotic-arm required' },
    regulatory: { fdaClearance: 'K210345', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400230008', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['knee', 'partial-knee', 'unicompartmental', 'mako-compatible', 'restoris'],
  },
  {
    maId: 'PRD-031',
    maName: 'Exeter Hip Stem',
    maDescription: 'Double-tapered polished cemented femoral stem with over 50 years of clinical heritage. The gold standard in cemented hip arthroplasty with proven long-term survivorship.',
    division: 'Reconstructive',
    category: 'Hip Replacement',
    subcategory: 'Femoral Stems',
    sku: 'STR-EXE-STEM',
    price: 3800.00,
    listPrice: 4400.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/exeter-hero-image-v2?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { stemType: 'Double-tapered polished', fixation: 'Cemented', material: 'Orthinox stainless steel', offsets: 'Standard, high, and lateralized', stemSizes: '0 to 4', neckAngles: '125°, 130°, 135°' },
    regulatory: { fdaClearance: 'K190235', deviceClass: 'Class II', productCode: 'NTJ', gudid: '00884400230009', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    tags: ['hip', 'cemented', 'femoral-stem', 'exeter', 'proven'],
  },
  {
    maId: 'PRD-032',
    maName: 'Mako SmartRobotics Disposable Kit',
    maDescription: 'Single-use sterile instrument and drape kit for Mako robotic-arm assisted procedures. Includes all necessary disposable components for one surgical case.',
    division: 'Reconstructive',
    category: 'Robotic Surgery',
    subcategory: 'Consumables',
    sku: 'STR-MAKO-DISP',
    price: 1850.00,
    listPrice: 2100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Mako%204%20Family%204%204K%20with%20shadow3?$max_width_720$',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { contents: 'Sterile drape, array pins, registration probe, cutting accessories', compatibility: 'Mako SmartRobotics System', singleUse: 'Yes', sterilization: 'EtO sterilized' },
    regulatory: { fdaClearance: 'K211048', deviceClass: 'Class I', productCode: 'OWJ', gudid: '00884400230010', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 10,
    tags: ['mako', 'disposable', 'consumable', 'robotics', 'single-use'],
  },
];
