// Spine Division
export const spine = [
  {
    maId: 'PRD-009',
    maName: 'SpinalPak Non-Invasive Spine Fusion Stimulator',
    maDescription: 'External bone growth stimulator utilizing combined magnetic field (CMF) technology for non-invasive spinal fusion support. Lightweight, battery-powered design promotes compliance.',
    division: 'Spine',
    category: 'Biologics & Stimulation',
    subcategory: 'Bone Growth Stimulators',
    sku: 'STR-SPAK-CMF',
    price: 5400.00,
    listPrice: 6200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Serrato?$max_width_720$',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { technology: 'Combined Magnetic Field (CMF)', treatmentTime: '30 minutes per session', batteryLife: '180 sessions', weight: '1.2 lbs', indicatedUse: 'Adjunct to lumbar spinal fusion', wearMethod: 'Lumbar belt with integrated coil' },
    regulatory: { fdaClearance: 'K182345', deviceClass: 'Class III', productCode: 'OYC', gudid: '00884400089012', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    tags: ['spine', 'bone-growth-stimulator', 'non-invasive', 'fusion'],
  },
  {
    maId: 'PRD-033',
    maName: 'Serrato Posterior Stabilization System',
    maDescription: 'Comprehensive posterior spinal fixation system with polyaxial pedicle screws, reduction instrumentation, and pre-contoured rods for degenerative, deformity, and trauma indications.',
    division: 'Spine',
    category: 'Posterior Fixation',
    subcategory: 'Pedicle Screw Systems',
    sku: 'STR-SERR-PSS',
    price: 12500.00,
    listPrice: 14500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Serrato?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { screwDiameters: '4.5–8.5 mm', screwLengths: '25–60 mm', rodDiameters: '5.5 mm, 6.0 mm', rodMaterials: 'Titanium, CoCr', tulipType: 'Polyaxial, monoaxial, reduction', lockingMechanism: 'Top-loading set screw' },
    regulatory: { fdaClearance: 'K220345', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330001', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'pedicle-screw', 'posterior-fixation', 'polyaxial'],
  },
  {
    maId: 'PRD-034',
    maName: 'Tritanium PL Posterior Lumbar Cage',
    maDescription: '3D-printed titanium interbody cage for posterior lumbar interbody fusion (PLIF). Highly porous structure promotes bony through-growth for long-term stability.',
    division: 'Spine',
    category: 'Interbody Fusion',
    subcategory: 'Lumbar Cages',
    sku: 'STR-TRIT-PL',
    price: 6800.00,
    listPrice: 7800.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Tritanium%20PL?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Tritanium 3D-printed Ti', porosity: '~60%', heights: '8–16 mm', footprints: '24x10 to 32x12 mm', lordosis: '0°, 8°, 15°', graftWindow: 'Open central graft chamber' },
    regulatory: { fdaClearance: 'K220456', deviceClass: 'Class II', productCode: 'MQP', gudid: '00884400330002', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'interbody', 'PLIF', 'tritanium', '3d-printed', 'cage'],
  },
  {
    maId: 'PRD-035',
    maName: 'Tritanium TL Lateral Lumbar Cage',
    maDescription: '3D-printed titanium interbody cage for transforaminal and lateral lumbar interbody fusion. Large footprint maximizes endplate coverage and segmental lordosis restoration.',
    division: 'Spine',
    category: 'Interbody Fusion',
    subcategory: 'Lumbar Cages',
    sku: 'STR-TRIT-TL',
    price: 7500.00,
    listPrice: 8600.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Tritanium%20TL?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Tritanium 3D-printed Ti', heights: '8–18 mm', footprints: '40x18 to 55x22 mm', lordosis: '0°, 6°, 12°, 20°', approach: 'Lateral or TLIF' },
    regulatory: { fdaClearance: 'K220457', deviceClass: 'Class II', productCode: 'MQP', gudid: '00884400330003', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'interbody', 'TLIF', 'lateral', 'tritanium', 'cage'],
  },
  {
    maId: 'PRD-036',
    maName: 'Tritanium C Cervical Cage',
    maDescription: '3D-printed titanium interbody cage for anterior cervical discectomy and fusion (ACDF). Zero-profile design eliminates the need for an anterior plate in most cases.',
    division: 'Spine',
    category: 'Interbody Fusion',
    subcategory: 'Cervical Cages',
    sku: 'STR-TRIT-C',
    price: 5200.00,
    listPrice: 6000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Tritanium%20C?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Tritanium 3D-printed Ti', heights: '5–10 mm', footprints: '12x14 to 16x18 mm', lordosis: '0°, 7°', fixation: 'Integrated screw fixation (zero-profile)' },
    regulatory: { fdaClearance: 'K220458', deviceClass: 'Class II', productCode: 'MQP', gudid: '00884400330004', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'cervical', 'ACDF', 'tritanium', 'zero-profile', 'cage'],
  },
  {
    maId: 'PRD-037',
    maName: 'K2M MESA 2 Deformity System',
    maDescription: 'Advanced posterior spinal deformity correction system with multi-planar reduction capabilities. Designed for complex adult and pediatric spinal deformity reconstruction.',
    division: 'Spine',
    category: 'Posterior Fixation',
    subcategory: 'Deformity',
    sku: 'STR-K2M-MESA2',
    price: 18500.00,
    listPrice: 21000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/MESA%202%20Deformity?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { screwDiameters: '4.0–10.0 mm', rodDiameters: '5.5 mm, 6.0 mm', rodMaterials: 'Ti, CoCr, stainless steel', correctionTools: 'In-situ bending, derotation, compression/distraction', compatibility: 'MESA Rail and MESA Spire connectors' },
    regulatory: { fdaClearance: 'K210567', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330005', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 7,
    minOrderQuantity: 1,
    tags: ['spine', 'deformity', 'scoliosis', 'pedicle-screw', 'K2M'],
  },
  {
    maId: 'PRD-038',
    maName: 'K2M RAVINE Lateral Access System',
    maDescription: 'Minimally invasive lateral retractor system for transpsoas lumbar interbody fusion. Integrated neuromonitoring and expandable blade design minimize tissue disruption.',
    division: 'Spine',
    category: 'Surgical Access',
    subcategory: 'Lateral',
    sku: 'STR-K2M-RAVINE',
    price: 24000.00,
    listPrice: 27500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/RAVINE%20Lateral%20Access?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { bladeWidths: '18, 22, 26 mm', bladeLengths: '80, 100, 120 mm', lightSource: 'Integrated LED', neuromonitoring: 'Compatible with NVM5 and SafeOp', expansion: 'Continuously variable' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class I', productCode: 'HBY', gudid: '00884400330006', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 7,
    minOrderQuantity: 1,
    tags: ['spine', 'lateral', 'MIS', 'retractor', 'K2M', 'LLIF'],
  },
  {
    maId: 'PRD-039',
    maName: 'K2M EVEREST Minimally Invasive Pedicle Screw',
    maDescription: 'Low-profile minimally invasive pedicle screw system with percutaneous delivery. Extended tab design facilitates rod passage and reduction through small incisions.',
    division: 'Spine',
    category: 'Posterior Fixation',
    subcategory: 'MIS Screws',
    sku: 'STR-K2M-EVEREST',
    price: 9800.00,
    listPrice: 11200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/EVEREST%20Degenerative?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { screwDiameters: '5.0–8.5 mm', screwLengths: '30–55 mm', rodDiameter: '5.5 mm', deliveryMethod: 'Percutaneous cannulated', tulipType: 'Extended polyaxial', set_screw: 'Pre-loaded break-off' },
    regulatory: { fdaClearance: 'K210345', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330007', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'MIS', 'pedicle-screw', 'percutaneous', 'K2M'],
  },
  {
    maId: 'PRD-040',
    maName: 'Xia 3 Spinal System',
    maDescription: 'Versatile posterior spinal fixation platform for degenerative, trauma, and tumor indications. Streamlined instrumentation with broad implant portfolio for cervicothoracolumbar applications.',
    division: 'Spine',
    category: 'Posterior Fixation',
    subcategory: 'Comprehensive System',
    sku: 'STR-XIA3-SYS',
    price: 14200.00,
    listPrice: 16500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Xia%203?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { region: 'Cervicothoracolumbar', screwTypes: 'Polyaxial, monoaxial, offset, iliac', rodDiameters: '3.5, 5.5, 6.0 mm', crosslinks: 'Low-profile', indications: 'Degenerative, trauma, tumor, deformity' },
    regulatory: { fdaClearance: 'K200678', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330008', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'posterior-fixation', 'pedicle-screw', 'comprehensive'],
  },
  {
    maId: 'PRD-041',
    maName: 'Oasys Occipitocervicothoracic System',
    maDescription: 'Posterior fixation system spanning the occiput to the upper thoracic spine. Includes occipital plates, cervical lateral mass screws, and polyaxial pedicle screws.',
    division: 'Spine',
    category: 'Posterior Fixation',
    subcategory: 'Cervical',
    sku: 'STR-OASYS-OCT',
    price: 11500.00,
    listPrice: 13200.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Oasys?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { region: 'Occiput to T3', occipitalPlates: '4 sizes', cervicalScrews: 'Lateral mass and pedicle', rodDiameter: '3.5 mm', material: 'Titanium alloy' },
    regulatory: { fdaClearance: 'K200890', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330009', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'cervical', 'occipital', 'posterior-fixation'],
  },
  {
    maId: 'PRD-042',
    maName: 'Vectra Cervical Anterior Plate',
    maDescription: 'Low-profile anterior cervical plate with variable-angle locking screws for ACDF procedures. Integrated screw locking mechanism prevents screw backout.',
    division: 'Spine',
    category: 'Anterior Fixation',
    subcategory: 'Cervical Plates',
    sku: 'STR-VECTRA-ACP',
    price: 3500.00,
    listPrice: 4100.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Serrato?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { levels: '1–4 level plates', screwAngulation: '± 25° variable angle', material: 'Titanium alloy', thickness: '2.0 mm', screwDiameters: '4.0, 4.5 mm', locking: 'Integrated cam-lock' },
    regulatory: { fdaClearance: 'K210456', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330010', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    tags: ['spine', 'cervical', 'anterior-plate', 'ACDF', 'locking'],
  },
  {
    maId: 'PRD-043',
    maName: 'iFuse Bedrock Sacroiliac Fusion',
    maDescription: 'Minimally invasive sacroiliac joint fusion system using 3D-printed titanium implants. Designed for SI joint dysfunction with percutaneous surgical technique.',
    division: 'Spine',
    category: 'SI Joint Fusion',
    subcategory: 'Minimally Invasive',
    sku: 'STR-IFUSE-BR',
    price: 8200.00,
    listPrice: 9500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Xia%203?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '3D-printed titanium', implantSizes: '3 diameters, multiple lengths', approach: 'Lateral percutaneous', implantsPerCase: 'Typically 3', porosity: 'Fenestrated surface for bone in-growth' },
    regulatory: { fdaClearance: 'K220123', deviceClass: 'Class II', productCode: 'MQP', gudid: '00884400330011', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'SI-joint', 'fusion', 'MIS', 'sacroiliac'],
  },
  {
    maId: 'PRD-044',
    maName: 'SafeOp Neural InformatiX System',
    maDescription: 'Intraoperative neurophysiological monitoring (IONM) platform for spine surgery. Provides real-time nerve function monitoring including EMG, SSEP, and MEP modalities.',
    division: 'Spine',
    category: 'Neuromonitoring',
    subcategory: 'IONM Systems',
    sku: 'STR-SAFEOP-SYS',
    price: 125000.00,
    listPrice: 145000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Serrato?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: true,
    specifications: { modalities: 'EMG, SSEP, MEP, D-wave', channels: '32 channels', display: '15 in touchscreen', connectivity: 'Wi-Fi remote monitoring', electrodes: 'Proprietary needle and surface', software: 'SafeOp Neural InformatiX' },
    regulatory: { fdaClearance: 'K220234', deviceClass: 'Class II', productCode: 'GWE', gudid: '00884400330012', mdsrCompliant: true },
    availability: 'Made to Order',
    leadTimeDays: 21,
    minOrderQuantity: 1,
    tags: ['spine', 'neuromonitoring', 'IONM', 'EMG', 'intraoperative'],
  },
  {
    maId: 'PRD-045',
    maName: 'Longitude II Posterior Fixation',
    maDescription: 'Multi-level posterior thoracolumbar fixation system with versatile reduction capabilities. Designed for complex reconstructions requiring long-segment stabilization.',
    division: 'Spine',
    category: 'Posterior Fixation',
    subcategory: 'Thoracolumbar',
    sku: 'STR-LONG2-PSF',
    price: 16000.00,
    listPrice: 18500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Xia%203?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { screwDiameters: '5.0–9.0 mm', rodDiameters: '5.5, 6.0, 6.35 mm', rodMaterials: 'Ti and CoCr', domainConnectors: 'Side-to-side, parallel, cross-link', region: 'T1 to sacrum/ilium' },
    regulatory: { fdaClearance: 'K210789', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330013', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['spine', 'posterior-fixation', 'thoracolumbar', 'multi-level'],
  },
  {
    maId: 'PRD-046',
    maName: 'Kaneda Anterior Scoliosis System',
    maDescription: 'Anterior vertebral body staple and rod system for thoracolumbar scoliosis correction. Low-profile design minimizes prominence while providing robust correction.',
    division: 'Spine',
    category: 'Anterior Fixation',
    subcategory: 'Deformity',
    sku: 'STR-KANEDA-SCOL',
    price: 13500.00,
    listPrice: 15500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/EVEREST%20Degenerative?$max_width_720$',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { approach: 'Anterior thoracolumbar', stapleType: 'Vertebral body', rodDiameter: '6.0 mm', material: 'Titanium alloy', indications: 'Adolescent idiopathic scoliosis' },
    regulatory: { fdaClearance: 'K200456', deviceClass: 'Class II', productCode: 'KWP', gudid: '00884400330014', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 7,
    minOrderQuantity: 1,
    tags: ['spine', 'anterior', 'scoliosis', 'deformity', 'thoracolumbar'],
  },
];
