// Sustainability Solutions Division
export const sustainability = [
  {
    maId: 'PRD-146', maName: 'Single-Use Device Reprocessing Program',
    maDescription: 'FDA-cleared reprocessing program for single-use medical devices. Collects, reprocesses, and returns devices at significant cost savings while diverting waste from landfills.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Device Reprocessing',
    sku: 'STR-SUS-REPRO-PROG', price: 0.00, listPrice: 0.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_SterileProcessing?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { deviceCategories: 'EP catheters, compression sleeves, trocars, blades, burs', fdaCleared: 'Yes — all reprocessed devices', savingsRange: '30–50% vs. new OEM', qualityStandard: 'ISO 13485 certified', collectionFrequency: 'Weekly scheduled pickups' },
    regulatory: { fdaClearance: 'Multiple 510(k) clearances', deviceClass: 'Varies by device', productCode: 'Varies', gudid: 'N/A — Service', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['sustainability', 'reprocessing', 'cost-savings', 'waste-reduction'],
  },
  {
    maId: 'PRD-147', maName: 'Reprocessed EP Catheter Collection',
    maDescription: 'FDA-cleared reprocessed electrophysiology diagnostic catheters. Same performance as new at a fraction of the cost with full traceability.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Electrophysiology',
    sku: 'STR-SUS-EP-CATH', price: 180.00, listPrice: 450.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/AXS-Catalyst-7?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { type: 'Diagnostic EP catheters', electrodes: '4, 10, 20 pole options', clearing: 'FDA 510(k) cleared', testing: '100% functional and sterility tested', packaging: 'Individual sterile packaging' },
    regulatory: { fdaClearance: 'K192345', deviceClass: 'Class II', productCode: 'DRE', gudid: '00884400146001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 10,
    tags: ['sustainability', 'reprocessing', 'EP', 'catheter', 'electrophysiology'],
  },
  {
    maId: 'PRD-148', maName: 'Reprocessed Compression Sleeves (Case of 50)',
    maDescription: 'FDA-cleared reprocessed sequential compression device sleeves. Validated cleaning, functional testing, and resterilization for cost-effective DVT prevention.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Compression',
    sku: 'STR-SUS-COMP-SLV', price: 425.00, listPrice: 950.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/heel-protector-collage-v4?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { quantity: '50 per case', sizes: 'Small, medium, large, X-large', type: 'Knee-length and thigh-length', cycles: 'Validated for reprocessing', savings: '~55% vs. new' },
    regulatory: { fdaClearance: 'K193456', deviceClass: 'Class II', productCode: 'DSZ', gudid: '00884400147001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['sustainability', 'reprocessing', 'compression', 'DVT-prevention'],
  },
  {
    maId: 'PRD-149', maName: 'Reprocessed Trocars and Cannulas',
    maDescription: 'FDA-cleared reprocessed laparoscopic trocars and cannulas for minimally invasive surgery. Full functional testing with guaranteed sharpness and seal integrity.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Laparoscopic',
    sku: 'STR-SUS-TROCAR', price: 65.00, listPrice: 160.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_Neptune3?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { sizes: '5 mm, 10 mm, 12 mm', types: 'Bladeless and bladed', sealType: 'Universal seal validated', sharpness: 'Penetration force tested', sterility: 'EtO sterilized' },
    regulatory: { fdaClearance: 'K194567', deviceClass: 'Class II', productCode: 'GEH', gudid: '00884400148001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 20,
    tags: ['sustainability', 'reprocessing', 'trocar', 'laparoscopic'],
  },
  {
    maId: 'PRD-150', maName: 'Reprocessed Ultrasonic Shear Blades',
    maDescription: 'FDA-cleared reprocessed harmonic scalpel blades. Validated cutting performance and hemostasis equivalent to new devices at reduced cost.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Energy',
    sku: 'STR-SUS-HARM-BLD', price: 220.00, listPrice: 550.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Photonblade?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { type: 'Ultrasonic cutting/coagulation', lengths: '36 cm, 23 cm, 14 cm', testing: 'Cutting speed and hemostasis validated', compatibility: 'Major ultrasonic generator platforms', savings: '~60% vs. new' },
    regulatory: { fdaClearance: 'K195678', deviceClass: 'Class II', productCode: 'GEI', gudid: '00884400149001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 10,
    tags: ['sustainability', 'reprocessing', 'ultrasonic', 'energy', 'harmonic'],
  },
  {
    maId: 'PRD-151', maName: 'Reprocessed Arthroscopic Shaver Blades',
    maDescription: 'FDA-cleared reprocessed arthroscopic shaver blades for sports medicine and joint procedures. Functional equivalence validated through rigorous testing protocols.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Arthroscopy',
    sku: 'STR-SUS-SHAVER-BLD', price: 45.00, listPrice: 110.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Shavers-Thumb?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { types: 'Full radius, aggressive, incisor', sizes: '3.5 mm, 4.0 mm, 5.0 mm', rpm: 'Validated to OEM spec', oscillation: 'Full oscillation tested', savings: '~60% vs. new' },
    regulatory: { fdaClearance: 'K196789', deviceClass: 'Class II', productCode: 'GEH', gudid: '00884400150001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 20,
    tags: ['sustainability', 'reprocessing', 'shaver', 'arthroscopy'],
  },
  {
    maId: 'PRD-152', maName: 'Blue Wrap Recycling Program',
    maDescription: 'Hospital blue wrap collection and recycling program converting sterilization wrap into useful products. Diverts polypropylene waste from landfills.',
    division: 'Sustainability Solutions', category: 'Recycling', subcategory: 'Blue Wrap',
    sku: 'STR-SUS-BLUEWRAP', price: 0.00, listPrice: 0.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_SterileProcessing?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { material: 'Polypropylene (blue wrap)', collection: 'On-site collection bins provided', pickup: 'Scheduled pickup service', output: 'Recycled into new products', reporting: 'Monthly diversion reports', certification: 'Chain of custody documentation' },
    regulatory: { fdaClearance: 'N/A — Recycling Service', deviceClass: 'N/A', productCode: 'N/A', gudid: 'N/A', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['sustainability', 'recycling', 'blue-wrap', 'waste-diversion'],
  },
  {
    maId: 'PRD-153', maName: 'Sustainability Impact Dashboard',
    maDescription: 'Digital platform tracking environmental and financial impact of sustainability programs. Real-time metrics on waste diversion, cost savings, and carbon reduction.',
    division: 'Sustainability Solutions', category: 'Digital Solutions', subcategory: 'Analytics',
    sku: 'STR-SUS-DASHBOARD', price: 12000.00, listPrice: 15000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Q-Guidance_2022-2?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: true,
    specifications: { metrics: 'Waste diverted, CO2 avoided, cost savings', reporting: 'Automated monthly and annual reports', benchmarking: 'Peer hospital comparison', access: 'Web-based, multi-user', exports: 'ESG reporting compatible' },
    regulatory: { fdaClearance: 'N/A — Software', deviceClass: 'N/A', productCode: 'N/A', gudid: 'N/A', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 7, minOrderQuantity: 1,
    tags: ['sustainability', 'digital', 'dashboard', 'analytics', 'ESG'],
  },
  {
    maId: 'PRD-154', maName: 'Medical Device Collection & Recycling',
    maDescription: 'End-of-life medical device collection and recycling program. Responsible disposal of retired capital equipment and single-use devices with certified material recovery.',
    division: 'Sustainability Solutions', category: 'Recycling', subcategory: 'Device Recycling',
    sku: 'STR-SUS-DEV-RECYCLE', price: 0.00, listPrice: 0.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Thumbnail_SterileProcessing?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { devices: 'Capital equipment, instruments, implants', process: 'Disassembly, material segregation, recycling', metals: 'Titanium, stainless steel, cobalt-chrome recovery', documentation: 'Certificate of recycling', compliance: 'EPA and state regulations' },
    regulatory: { fdaClearance: 'N/A — Recycling Service', deviceClass: 'N/A', productCode: 'N/A', gudid: 'N/A', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['sustainability', 'recycling', 'end-of-life', 'material-recovery'],
  },
  {
    maId: 'PRD-155', maName: 'Reprocessed Pulse Oximeter Sensors (Box of 24)',
    maDescription: 'FDA-cleared reprocessed pulse oximetry sensors. Validated SpO2 accuracy and adhesion performance equivalent to new sensors.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Monitoring',
    sku: 'STR-SUS-PULSEOX', price: 95.00, listPrice: 220.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/LIFEPAK_15_V4_Hospital?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { quantity: '24 per box', type: 'Adult finger clip and adhesive', accuracy: '±2% SpO2 (70–100%)', compatibility: 'Major patient monitor platforms', adhesion: 'Validated adhesive performance' },
    regulatory: { fdaClearance: 'K197890', deviceClass: 'Class II', productCode: 'DQA', gudid: '00884400154001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 1,
    tags: ['sustainability', 'reprocessing', 'pulse-oximetry', 'monitoring'],
  },
  {
    maId: 'PRD-156', maName: 'Sustainability Consulting Engagement',
    maDescription: 'Comprehensive hospital sustainability assessment and strategy consulting. Waste stream audit, reprocessing opportunity analysis, and environmental impact reduction roadmap.',
    division: 'Sustainability Solutions', category: 'Consulting', subcategory: 'Strategy',
    sku: 'STR-SUS-CONSULT', price: 25000.00, listPrice: 30000.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/OR-integration-specialty-hero-v2?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { duration: '6–8 weeks', phases: 'Waste audit, opportunity analysis, implementation plan', deliverables: 'Sustainability roadmap, ROI projections, ESG metrics', focus: 'OR waste, reprocessing, recycling, energy', benchmarking: 'Industry sustainability benchmarks' },
    regulatory: { fdaClearance: 'N/A — Service', deviceClass: 'N/A', productCode: 'N/A', gudid: 'N/A', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 14, minOrderQuantity: 1,
    tags: ['sustainability', 'consulting', 'waste-audit', 'ESG', 'strategy'],
  },
  {
    maId: 'PRD-157', maName: 'Reprocessed Bipolar Forceps',
    maDescription: 'FDA-cleared reprocessed bipolar electrosurgical forceps for precise tissue coagulation. Insulation integrity and tip alignment validated through automated inspection.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Electrosurgery',
    sku: 'STR-SUS-BIPOLAR', price: 35.00, listPrice: 85.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Photonblade?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { types: 'Bayonet, Cushing, Gerald', lengths: '7 in, 8.5 in, 10 in', tipWidths: '0.5 mm, 1.0 mm, 1.5 mm', testing: 'Insulation and alignment inspection', savings: '~60% vs. new' },
    regulatory: { fdaClearance: 'K198901', deviceClass: 'Class II', productCode: 'GEI', gudid: '00884400156001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 20,
    tags: ['sustainability', 'reprocessing', 'bipolar', 'electrosurgery'],
  },
  {
    maId: 'PRD-158', maName: 'Reprocessed LigaSure Vessel Sealing Devices',
    maDescription: 'FDA-cleared reprocessed vessel sealing instruments for open and laparoscopic surgery. Seal strength and burst pressure validated to OEM specifications.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Energy',
    sku: 'STR-SUS-LIGASURE', price: 195.00, listPrice: 480.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Photonblade?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { types: 'Open and laparoscopic', jawLengths: '20 mm, 37 mm', sealStrength: 'Validated to OEM burst pressure', cutting: 'Integrated knife tested', savings: '~60% vs. new' },
    regulatory: { fdaClearance: 'K199012', deviceClass: 'Class II', productCode: 'GEI', gudid: '00884400157001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 3, minOrderQuantity: 10,
    tags: ['sustainability', 'reprocessing', 'vessel-sealing', 'energy'],
  },
  {
    maId: 'PRD-159', maName: 'Green OR Implementation Kit',
    maDescription: 'Comprehensive toolkit for implementing a Green OR program. Includes waste segregation guides, staff training materials, tracking tools, and best practice playbooks.',
    division: 'Sustainability Solutions', category: 'Programs', subcategory: 'Green OR',
    sku: 'STR-SUS-GREEN-OR', price: 5000.00, listPrice: 6500.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/OR-integration-specialty-hero-v2?$max_width_720$',
    isConfigurable: true, isSerialManaged: false, isBatchManaged: false, isSubscriptionEligible: false,
    specifications: { components: 'Waste guides, training modules, tracking tools', format: 'Digital + printed materials', training: 'Train-the-trainer program', duration: 'Self-paced implementation', support: '6 months advisory support', metrics: 'Waste reduction tracking framework' },
    regulatory: { fdaClearance: 'N/A — Education', deviceClass: 'N/A', productCode: 'N/A', gudid: 'N/A', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['sustainability', 'green-OR', 'waste-reduction', 'training', 'implementation'],
  },
  {
    maId: 'PRD-160', maName: 'Reprocessed External Fixation Pins (Box of 50)',
    maDescription: 'FDA-cleared reprocessed external fixation half-pins for orthopedic trauma. Validated thread integrity, sharpness, and corrosion resistance.',
    division: 'Sustainability Solutions', category: 'Reprocessing', subcategory: 'Orthopedic',
    sku: 'STR-SUS-EXFIX-PIN', price: 280.00, listPrice: 625.00,
    imageUrl: 'https://media-assets.stryker.com/is/image/stryker/Hoffmann3?$max_width_720$',
    isConfigurable: false, isSerialManaged: false, isBatchManaged: true, isSubscriptionEligible: true,
    specifications: { quantity: '50 per box', diameters: '4.0 mm, 5.0 mm, 6.0 mm', material: 'Stainless steel', testing: 'Thread integrity, bending strength, sharpness', sterility: 'Gamma irradiation sterilized' },
    regulatory: { fdaClearance: 'K199123', deviceClass: 'Class II', productCode: 'HRS', gudid: '00884400159001', mdsrCompliant: true },
    availability: 'In Stock', leadTimeDays: 5, minOrderQuantity: 1,
    tags: ['sustainability', 'reprocessing', 'external-fixation', 'orthopedic', 'trauma'],
  },
];
