// Mock product documentation for Stryker B2B Portal
// Types: User Manual, IFU, Quick Reference, Service Manual, Brochure, White Paper, Regulatory

export const documentation = [
  {
    id: 'DOC-001',
    title: 'System 8 Power Tools — Instructions for Use',
    type: 'IFU',
    productIds: ['PRD-001', 'PRD-002'],
    productNames: ['System 8 Large Bone Power Tool Set', 'System 8 Small Bone Power Tool Set'],
    division: 'Instruments',
    description:
      'Complete instructions for use including indications, contraindications, sterilization guidelines, assembly, operation, and maintenance of System 8 power tools.',
    version: '3.1',
    language: 'en-US',
    publishDate: '2024-06-15T00:00:00Z',
    lastUpdated: '2024-06-15T00:00:00Z',
    fileUrl: '/docs/system-8-ifu-v3.1.pdf',
    fileSize: '4.2 MB',
    pageCount: 68,
    documentNumber: 'IFU-8000-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['power-tools', 'system-8', 'IFU', 'sterilization', 'safety'],
  },
  {
    id: 'DOC-002',
    title: 'Neptune 3 Waste Management — Operator Manual',
    type: 'User Manual',
    productIds: ['PRD-003'],
    productNames: ['Neptune 3 Waste Management System'],
    division: 'Healthcare Systems, MedSurg',
    description:
      'Comprehensive operator manual covering setup, daily operation, filter replacement, troubleshooting, and cleaning procedures for the Neptune 3 system.',
    version: '2.0',
    language: 'en-US',
    publishDate: '2024-03-01T00:00:00Z',
    lastUpdated: '2024-09-10T00:00:00Z',
    fileUrl: '/docs/neptune-3-operator-manual-v2.0.pdf',
    fileSize: '8.7 MB',
    pageCount: 142,
    documentNumber: 'MAN-NEP3-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['neptune', 'waste-management', 'manual', 'operator', 'maintenance'],
  },
  {
    id: 'DOC-003',
    title: 'Secure II Hospital Bed — Service Manual',
    type: 'Service Manual',
    productIds: ['PRD-004'],
    productNames: ['Secure II Hospital Bed'],
    division: 'Medical',
    description:
      'Technical service manual for biomedical engineers and authorized service technicians. Includes electrical schematics, diagnostic procedures, preventive maintenance checklists, and parts lists.',
    version: '4.0',
    language: 'en-US',
    publishDate: '2024-01-15T00:00:00Z',
    lastUpdated: '2024-08-20T00:00:00Z',
    fileUrl: '/docs/secure-ii-service-manual-v4.0.pdf',
    fileSize: '15.3 MB',
    pageCount: 284,
    documentNumber: 'SVC-SEC2-EN-US',
    regulatoryClassification: 'Restricted — Authorized Service Personnel Only',
    accessLevel: 'service_personnel',
    tags: ['hospital-bed', 'secure-ii', 'service', 'maintenance', 'biomed', 'schematics'],
  },
  {
    id: 'DOC-004',
    title: 'Mako SmartRobotics System — Surgical Technique Guide (TKA)',
    type: 'Quick Reference',
    productIds: ['PRD-014', 'PRD-015'],
    productNames: ['Mako SmartRobotics System', 'Triathlon Total Knee System'],
    division: 'Reconstructive',
    description:
      'Step-by-step surgical technique guide for Mako robotic-arm assisted total knee arthroplasty using the Triathlon Knee System. Includes CT planning, registration, bone preparation, and implant placement.',
    version: '5.2',
    language: 'en-US',
    publishDate: '2024-09-01T00:00:00Z',
    lastUpdated: '2024-09-01T00:00:00Z',
    fileUrl: '/docs/mako-tka-technique-guide-v5.2.pdf',
    fileSize: '12.1 MB',
    pageCount: 96,
    documentNumber: 'TG-MAKO-TKA-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'medical_professionals',
    tags: ['mako', 'robotics', 'TKA', 'surgical-technique', 'triathlon', 'knee'],
  },
  {
    id: 'DOC-005',
    title: 'Triathlon Knee System — IFU',
    type: 'IFU',
    productIds: ['PRD-015'],
    productNames: ['Triathlon Total Knee System'],
    division: 'Reconstructive',
    description:
      'Instructions for use for the Triathlon Total Knee System including indications, sizing, implant selection, cement techniques, and post-operative care guidelines.',
    version: '6.0',
    language: 'en-US',
    publishDate: '2024-04-01T00:00:00Z',
    lastUpdated: '2024-04-01T00:00:00Z',
    fileUrl: '/docs/triathlon-knee-ifu-v6.0.pdf',
    fileSize: '5.8 MB',
    pageCount: 84,
    documentNumber: 'IFU-TRI-TKS-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['triathlon', 'knee', 'IFU', 'joint-replacement', 'implant'],
  },
  {
    id: 'DOC-006',
    title: 'Sonopet iQ — Quick Start Guide',
    type: 'Quick Reference',
    productIds: ['PRD-010'],
    productNames: ['Sonopet iQ Ultrasonic Aspirator'],
    division: 'Instruments',
    description:
      'Quick-start reference card for OR setup, handpiece assembly, tip selection, and basic operation of the Sonopet iQ ultrasonic aspirator system.',
    version: '1.3',
    language: 'en-US',
    publishDate: '2024-07-01T00:00:00Z',
    lastUpdated: '2024-07-01T00:00:00Z',
    fileUrl: '/docs/sonopet-iq-quick-start-v1.3.pdf',
    fileSize: '1.8 MB',
    pageCount: 8,
    documentNumber: 'QS-SPIQ-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['sonopet', 'neurosurgery', 'ultrasonic', 'quick-start', 'setup'],
  },
  {
    id: 'DOC-007',
    title: 'Target X Navigation — Clinical Evidence Summary',
    type: 'White Paper',
    productIds: ['PRD-011'],
    productNames: ['Target X Surgical Navigation System'],
    division: 'Instruments',
    description:
      'Peer-reviewed clinical evidence summary demonstrating accuracy, workflow efficiency, and outcomes data for the Target X electromagnetic surgical navigation platform in cranial and spinal procedures.',
    version: '2.0',
    language: 'en-US',
    publishDate: '2024-10-15T00:00:00Z',
    lastUpdated: '2024-10-15T00:00:00Z',
    fileUrl: '/docs/target-x-clinical-evidence-v2.0.pdf',
    fileSize: '3.4 MB',
    pageCount: 24,
    documentNumber: 'WP-TGTX-CLIN-EN-US',
    regulatoryClassification: 'Marketing Material',
    accessLevel: 'public',
    tags: ['navigation', 'clinical-evidence', 'white-paper', 'neurosurgery', 'spine'],
  },
  {
    id: 'DOC-008',
    title: 'LIFEPAK 15 — Operator Guide',
    type: 'User Manual',
    productIds: ['PRD-007'],
    productNames: ['LIFEPAK 15 Monitor/Defibrillator'],
    division: 'Medical',
    description:
      'Complete operator guide for the LIFEPAK 15 monitor/defibrillator covering setup, monitoring modes, defibrillation, pacing, 12-lead ECG, and data management.',
    version: '7.1',
    language: 'en-US',
    publishDate: '2024-02-01T00:00:00Z',
    lastUpdated: '2024-08-15T00:00:00Z',
    fileUrl: '/docs/lifepak-15-operator-guide-v7.1.pdf',
    fileSize: '11.2 MB',
    pageCount: 228,
    documentNumber: 'MAN-LP15-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['lifepak', 'defibrillator', 'manual', 'operator', 'emergency', 'ALS'],
  },
  {
    id: 'DOC-009',
    title: 'Accolade II & Trident II Hip System — Surgical Technique',
    type: 'Quick Reference',
    productIds: ['PRD-016', 'PRD-008'],
    productNames: ['Accolade II Femoral Hip Stem', 'Trident II Acetabular System'],
    division: 'Reconstructive',
    description:
      'Illustrated surgical technique guide for primary total hip arthroplasty using the Accolade II stem and Trident II acetabular system. Includes templating, approach selection, and implant sizing.',
    version: '3.0',
    language: 'en-US',
    publishDate: '2024-05-01T00:00:00Z',
    lastUpdated: '2024-05-01T00:00:00Z',
    fileUrl: '/docs/accolade-trident-technique-v3.0.pdf',
    fileSize: '9.6 MB',
    pageCount: 72,
    documentNumber: 'TG-ACC2-TRD2-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'medical_professionals',
    tags: ['hip', 'surgical-technique', 'accolade', 'trident', 'joint-replacement', 'THA'],
  },
  {
    id: 'DOC-010',
    title: 'Stryker B2B Portal — Ordering and Account Management Guide',
    type: 'User Manual',
    productIds: [],
    productNames: [],
    division: 'General',
    description:
      'User guide for the Stryker B2B customer portal. Covers account setup, product search, ordering, order tracking, invoice management, consignment inventory, and subscription management.',
    version: '1.0',
    language: 'en-US',
    publishDate: '2025-01-01T00:00:00Z',
    lastUpdated: '2025-01-01T00:00:00Z',
    fileUrl: '/docs/b2b-portal-user-guide-v1.0.pdf',
    fileSize: '6.4 MB',
    pageCount: 52,
    documentNumber: 'MAN-B2B-PORTAL-EN-US',
    regulatoryClassification: 'Non-Regulated',
    accessLevel: 'registered_users',
    tags: ['portal', 'user-guide', 'ordering', 'account-management', 'help'],
  },
];

export const getDocumentById = (id) => documentation.find((d) => d.id === id);
export const getDocumentsByProduct = (productId) =>
  documentation.filter((d) => d.productIds.includes(productId));
export const getDocumentsByType = (type) => documentation.filter((d) => d.type === type);
export const getDocumentsByDivision = (division) =>
  documentation.filter((d) => d.division === division);

export const documentTypes = [
  'User Manual',
  'IFU',
  'Quick Reference',
  'Service Manual',
  'Brochure',
  'White Paper',
  'Regulatory',
];

export default documentation;
