// Mock orders for Stryker B2B Portal
// Various statuses: Draft, Submitted, Confirmed, Shipped, Delivered, Invoiced, Cancelled

export const orders = [
  {
    biId: 'ORD-2025-0001',
    biName: 'Northwest Medical — Mako System Order',
    biDescription: 'Mako SmartRobotics System with installation and training package for new orthopedic wing.',
    status: 'Confirmed',
    priority: 'High',
    biCreatedAt: '2025-01-02T09:15:00Z',
    biUpdatedAt: '2025-01-05T14:30:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-014',
        productName: 'Mako SmartRobotics System',
        sku: 'STR-MAKO-SYS-4',
        quantity: 1,
        unitPrice: 1250000.0,
        discount: 50000.0,
        lineTotal: 1200000.0,
        configuration: 'TKA + THA Application Bundle',
      },
    ],
    pricing: {
      subtotal: 1200000.0,
      discount: 50000.0,
      tax: 102000.0,
      freight: 8500.0,
      total: 1310500.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Northwest Medical Center — OR Suite',
      street: '1200 Madison Ave',
      building: 'Surgical Pavilion, Dock B',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 60',
    requestedDeliveryDate: '2025-03-15T00:00:00Z',
    contractId: 'CTR-NWM-2024-001',
    notes: 'Installation requires 2-week lead time. Coordinate with facilities management.',
  },
  {
    biId: 'ORD-2025-0002',
    biName: 'Mercy Health — Triathlon Knee Implants',
    biDescription: 'Quarterly restock of Triathlon Total Knee System components for three facilities.',
    status: 'Shipped',
    priority: 'Standard',
    biCreatedAt: '2024-12-18T11:00:00Z',
    biUpdatedAt: '2025-01-08T08:45:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-015',
        productName: 'Triathlon Total Knee System',
        sku: 'STR-TRI-TKS',
        quantity: 24,
        unitPrice: 8500.0,
        discount: 0,
        lineTotal: 204000.0,
        configuration: 'CR Bearing, Sizes 3-7',
      },
      {
        lineNumber: 2,
        productId: 'PRD-016',
        productName: 'Accolade II Femoral Hip Stem',
        sku: 'STR-ACC2-STEM',
        quantity: 12,
        unitPrice: 5200.0,
        discount: 0,
        lineTotal: 62400.0,
        configuration: 'Standard Offset, Sizes 2-6',
      },
    ],
    pricing: {
      subtotal: 266400.0,
      discount: 13320.0,
      tax: 21510.48,
      freight: 1200.0,
      total: 275790.48,
      currency: 'USD',
    },
    shipTo: {
      name: 'Mercy West Hospital — Central Supply',
      street: '615 Elsinore Pl',
      building: 'Central Warehouse',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2025-01-10T00:00:00Z',
    contractId: 'CTR-MHS-2024-003',
    notes: 'Split shipment across three facilities per distribution list.',
  },
  {
    biId: 'ORD-2025-0003',
    biName: 'MedSupply Pro — System 8 Bulk Order',
    biDescription: 'Distributor bulk order for System 8 power tools and battery packs.',
    status: 'Delivered',
    priority: 'Standard',
    biCreatedAt: '2024-11-20T14:30:00Z',
    biUpdatedAt: '2024-12-15T10:00:00Z',
    biCompletedAt: '2024-12-15T10:00:00Z',
    customer: {
      id: 'ORG-002',
      name: 'MedSupply Pro Distribution',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@medsupplypro.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'System 8 Large Bone Power Tool Set',
        sku: 'STR-8000-LB-SET',
        quantity: 10,
        unitPrice: 18750.0,
        discount: 1875.0,
        lineTotal: 168750.0,
        configuration: 'Standard Configuration',
      },
      {
        lineNumber: 2,
        productId: 'PRD-002',
        productName: 'System 8 Small Bone Power Tool Set',
        sku: 'STR-8000-SB-SET',
        quantity: 10,
        unitPrice: 15200.0,
        discount: 1520.0,
        lineTotal: 136800.0,
        configuration: 'Standard Configuration',
      },
      {
        lineNumber: 3,
        productId: 'PRD-022',
        productName: 'System 8 SmartLife Battery Pack',
        sku: 'STR-8000-BATT',
        quantity: 40,
        unitPrice: 2850.0,
        discount: 285.0,
        lineTotal: 102600.0,
      },
    ],
    pricing: {
      subtotal: 408150.0,
      discount: 44310.0,
      tax: 0.0,
      freight: 2800.0,
      total: 410950.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'MedSupply Pro — Main Warehouse',
      street: '4500 W Diversey Ave',
      building: 'Building C, Dock 4',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2024-12-12T00:00:00Z',
    contractId: 'CTR-MSP-2024-007',
    notes: 'Distributor pricing tier applied. Tax exempt — resale certificate on file.',
  },
  {
    biId: 'ORD-2025-0004',
    biName: 'Northwest Medical — Neptune 3 System',
    biDescription: 'Neptune 3 Waste Management System for new OR suites with consumable subscription.',
    status: 'Invoiced',
    priority: 'Standard',
    biCreatedAt: '2024-10-15T08:00:00Z',
    biUpdatedAt: '2024-11-30T16:00:00Z',
    biCompletedAt: '2024-11-28T14:30:00Z',
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-003',
        productName: 'Neptune 3 Waste Management System',
        sku: 'STR-NEP3-SYS',
        quantity: 4,
        unitPrice: 42500.0,
        discount: 4250.0,
        lineTotal: 153000.0,
        configuration: 'Standard with ULPA upgrade',
      },
      {
        lineNumber: 2,
        productId: 'PRD-021',
        productName: 'Neptune 3 Disposable Canister Set (Case of 12)',
        sku: 'STR-NEP3-CAN-12',
        quantity: 20,
        unitPrice: 680.0,
        discount: 0,
        lineTotal: 13600.0,
      },
    ],
    pricing: {
      subtotal: 166600.0,
      discount: 17000.0,
      tax: 12726.0,
      freight: 3200.0,
      total: 165526.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Northwest Medical Center — Facilities',
      street: '1200 Madison Ave',
      building: 'Facilities Receiving, Dock A',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 60',
    requestedDeliveryDate: '2024-11-20T00:00:00Z',
    contractId: 'CTR-NWM-2024-001',
    notes: 'Consumable subscription setup after install. See SUB-001.',
  },
  {
    biId: 'ORD-2025-0005',
    biName: 'Mercy Health — Secure II Beds',
    biDescription: 'Hospital bed replacement program — Phase 1 for Mercy West ICU.',
    status: 'Delivered',
    priority: 'Standard',
    biCreatedAt: '2024-09-05T10:30:00Z',
    biUpdatedAt: '2024-10-22T09:15:00Z',
    biCompletedAt: '2024-10-22T09:15:00Z',
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-004',
        productName: 'Secure II Hospital Bed',
        sku: 'STR-SEC2-BED',
        quantity: 30,
        unitPrice: 14800.0,
        discount: 1480.0,
        lineTotal: 399600.0,
        configuration: 'ICU Configuration with Scale',
      },
    ],
    pricing: {
      subtotal: 399600.0,
      discount: 44400.0,
      tax: 30196.8,
      freight: 6500.0,
      total: 392296.8,
      currency: 'USD',
    },
    shipTo: {
      name: 'Mercy West Hospital — ICU Wing',
      street: '615 Elsinore Pl',
      building: 'West Wing, Floor 3 Loading',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    paymentTerms: 'Net 60',
    requestedDeliveryDate: '2024-10-15T00:00:00Z',
    contractId: 'CTR-MHS-2024-003',
    notes: 'Phase 1 of 3. Phase 2 for Fairfield facility Q1 2025.',
  },
  {
    biId: 'ORD-2025-0006',
    biName: 'Northwest Medical — Sonopet iQ',
    biDescription: 'Sonopet iQ Ultrasonic Aspirator for neurosurgery department expansion.',
    status: 'Submitted',
    priority: 'High',
    biCreatedAt: '2025-01-10T16:00:00Z',
    biUpdatedAt: '2025-01-10T16:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-010',
        productName: 'Sonopet iQ Ultrasonic Aspirator',
        sku: 'STR-SPIQ-SYS',
        quantity: 2,
        unitPrice: 67500.0,
        discount: 6750.0,
        lineTotal: 121500.0,
        configuration: 'Full tip set with iQ Intelligence module',
      },
    ],
    pricing: {
      subtotal: 121500.0,
      discount: 13500.0,
      tax: 9180.0,
      freight: 1500.0,
      total: 118680.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Northwest Medical Center — Neuro OR',
      street: '1200 Madison Ave',
      building: 'Neuroscience Center, Floor 4',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 60',
    requestedDeliveryDate: '2025-02-15T00:00:00Z',
    contractId: 'CTR-NWM-2024-001',
    notes: 'Pending credit approval. Expedited shipping requested.',
  },
  {
    biId: 'ORD-2025-0007',
    biName: 'MedSupply Pro — Trauma Fixation Restock',
    biDescription: 'Distributor restock of trauma fixation products.',
    status: 'Confirmed',
    priority: 'Standard',
    biCreatedAt: '2025-01-08T13:45:00Z',
    biUpdatedAt: '2025-01-12T09:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-002',
      name: 'MedSupply Pro Distribution',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@medsupplypro.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-017',
        productName: 'VariAx 2 Distal Radius Locking Plate System',
        sku: 'STR-VAX2-DR',
        quantity: 50,
        unitPrice: 2100.0,
        discount: 210.0,
        lineTotal: 94500.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-018',
        productName: 'T2 Alpha Femoral Nailing System',
        sku: 'STR-T2A-FEM',
        quantity: 20,
        unitPrice: 4800.0,
        discount: 480.0,
        lineTotal: 86400.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-019',
        productName: 'Hoffman 3 External Fixation System',
        sku: 'STR-HF3-EXFIX',
        quantity: 15,
        unitPrice: 3600.0,
        discount: 360.0,
        lineTotal: 48600.0,
      },
    ],
    pricing: {
      subtotal: 229500.0,
      discount: 23100.0,
      tax: 0.0,
      freight: 1850.0,
      total: 208250.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'MedSupply Pro — Main Warehouse',
      street: '4500 W Diversey Ave',
      building: 'Building C, Dock 4',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-01-22T00:00:00Z',
    contractId: 'CTR-MSP-2024-007',
    notes: 'Tax exempt — distributor resale.',
  },
  {
    biId: 'ORD-2025-0008',
    biName: 'Pacific Surgical — LIFEPAK 15 Units',
    biDescription: 'Emergency department defibrillator fleet replacement.',
    status: 'Draft',
    priority: 'Low',
    biCreatedAt: '2025-01-14T10:20:00Z',
    biUpdatedAt: '2025-01-14T10:20:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-004',
      name: 'Pacific Surgical Associates',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@pacificsurgical.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-007',
        productName: 'LIFEPAK 15 Monitor/Defibrillator',
        sku: 'STR-LP15-FULL',
        quantity: 6,
        unitPrice: 28900.0,
        discount: 0,
        lineTotal: 173400.0,
        configuration: 'Full monitoring: SpO2, EtCO2, 12-lead ECG',
      },
    ],
    pricing: {
      subtotal: 173400.0,
      discount: 0,
      tax: 14739.0,
      freight: 900.0,
      total: 189039.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Pacific Surgical Associates',
      street: '900 Pacific Ave',
      building: 'Suite 200',
      city: 'Tacoma',
      state: 'WA',
      zip: '98402',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-03-01T00:00:00Z',
    contractId: null,
    notes: 'Draft — awaiting budget approval from hospital board.',
  },
  {
    biId: 'ORD-2025-0009',
    biName: 'Mercy Health — T5 Stretchers',
    biDescription: 'T5 Prime stretcher fleet for new emergency department.',
    status: 'Shipped',
    priority: 'Standard',
    biCreatedAt: '2024-12-05T09:00:00Z',
    biUpdatedAt: '2025-01-06T11:30:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-006',
        productName: 'T5 Prime Powered Stretcher',
        sku: 'STR-T5P-STRETCH',
        quantity: 15,
        unitPrice: 22300.0,
        discount: 2230.0,
        lineTotal: 301050.0,
        configuration: 'Standard with IV pole and O2 holder',
      },
    ],
    pricing: {
      subtotal: 301050.0,
      discount: 33450.0,
      tax: 22730.1,
      freight: 4200.0,
      total: 294530.1,
      currency: 'USD',
    },
    shipTo: {
      name: 'Mercy Anderson Hospital — ED',
      street: '7500 State Rd',
      building: 'Emergency Department Receiving',
      city: 'Anderson',
      state: 'OH',
      zip: '45230',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2025-01-10T00:00:00Z',
    contractId: 'CTR-MHS-2024-003',
    notes: 'Partial delivery accepted. Final 5 units shipping week of Jan 13.',
  },
  {
    biId: 'ORD-2025-0010',
    biName: 'Northwest Medical — Spine Navigation',
    biDescription: 'Target X Navigation System for spine surgery program.',
    status: 'Confirmed',
    priority: 'High',
    biCreatedAt: '2024-12-20T15:00:00Z',
    biUpdatedAt: '2025-01-10T08:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-011',
        productName: 'Target X Surgical Navigation System',
        sku: 'STR-TGTX-NAV',
        quantity: 1,
        unitPrice: 285000.0,
        discount: 28500.0,
        lineTotal: 256500.0,
        configuration: 'Cranial + Spine software suite',
      },
    ],
    pricing: {
      subtotal: 256500.0,
      discount: 28500.0,
      tax: 21802.5,
      freight: 3500.0,
      total: 253302.5,
      currency: 'USD',
    },
    shipTo: {
      name: 'Northwest Medical Center — Spine OR',
      street: '1200 Madison Ave',
      building: 'Neuroscience Center, Floor 3',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 60',
    requestedDeliveryDate: '2025-02-28T00:00:00Z',
    contractId: 'CTR-NWM-2024-001',
    notes: 'Made to order. Estimated build time 4 weeks.',
  },
  {
    biId: 'ORD-2024-0011',
    biName: 'Cascade Regional — Shoulder Implants',
    biDescription: 'Tornier Perform Reversed Shoulder systems for orthopedic department.',
    status: 'Invoiced',
    priority: 'Standard',
    biCreatedAt: '2024-08-12T11:00:00Z',
    biUpdatedAt: '2024-09-30T14:00:00Z',
    biCompletedAt: '2024-09-25T16:45:00Z',
    customer: {
      id: 'ORG-005',
      name: 'Cascade Regional Medical Center',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@cascaderegional.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-020',
        productName: 'Tornier Perform Reversed Shoulder System',
        sku: 'STR-TOR-RSA',
        quantity: 8,
        unitPrice: 9200.0,
        discount: 0,
        lineTotal: 73600.0,
        configuration: '39mm Glenosphere, Standard Bearing',
      },
    ],
    pricing: {
      subtotal: 73600.0,
      discount: 0,
      tax: 6256.0,
      freight: 850.0,
      total: 80706.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Cascade Regional Medical Center',
      street: '2501 Mountain View Dr',
      building: 'Surgical Services',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2024-09-15T00:00:00Z',
    contractId: 'CTR-CRM-2024-001',
    notes: null,
  },
  {
    biId: 'ORD-2024-0012',
    biName: 'MedSupply Pro — SAGE Products Order',
    biDescription: 'Bulk order for SAGE Prevalon and CHG bathing products.',
    status: 'Delivered',
    priority: 'Standard',
    biCreatedAt: '2024-10-01T13:30:00Z',
    biUpdatedAt: '2024-10-18T08:00:00Z',
    biCompletedAt: '2024-10-18T08:00:00Z',
    customer: {
      id: 'ORG-002',
      name: 'MedSupply Pro Distribution',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@medsupplypro.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-005',
        productName: 'SAGE Prevalon Turn and Position System',
        sku: 'STR-SAGE-PTP-200',
        quantity: 100,
        unitPrice: 4250.0,
        discount: 637.5,
        lineTotal: 361250.0,
      },
    ],
    pricing: {
      subtotal: 361250.0,
      discount: 63750.0,
      tax: 0.0,
      freight: 3200.0,
      total: 300700.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'MedSupply Pro — Main Warehouse',
      street: '4500 W Diversey Ave',
      building: 'Building A',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2024-10-15T00:00:00Z',
    contractId: 'CTR-MSP-2024-007',
    notes: 'Tax exempt — distributor. Pallet delivery.',
  },
  {
    biId: 'ORD-2025-0013',
    biName: 'Mercy Health — Neurovascular Supplies',
    biDescription: 'Surpass Evolve flow diverters and SpinalPak stimulators.',
    status: 'Submitted',
    priority: 'Standard',
    biCreatedAt: '2025-01-13T14:15:00Z',
    biUpdatedAt: '2025-01-13T14:15:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-013',
        productName: 'Surpass Evolve Flow Diverter',
        sku: 'STR-SRPS-EVLV',
        quantity: 10,
        unitPrice: 12500.0,
        discount: 0,
        lineTotal: 125000.0,
        configuration: '4.0mm x 25mm',
      },
      {
        lineNumber: 2,
        productId: 'PRD-009',
        productName: 'SpinalPak Non-Invasive Spine Fusion Stimulator',
        sku: 'STR-SPAK-CMF',
        quantity: 6,
        unitPrice: 5400.0,
        discount: 0,
        lineTotal: 32400.0,
      },
    ],
    pricing: {
      subtotal: 157400.0,
      discount: 0,
      tax: 13379.0,
      freight: 600.0,
      total: 171379.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Mercy West Hospital — Interventional Neuro',
      street: '615 Elsinore Pl',
      building: 'Neurointerventional Suite',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2025-02-01T00:00:00Z',
    contractId: 'CTR-MHS-2024-003',
    notes: 'Pending clinical review confirmation.',
  },
  {
    biId: 'ORD-2024-0014',
    biName: 'Pacific Surgical — Shunt Order',
    biDescription: 'Neuro Matrix programmable shunt systems.',
    status: 'Cancelled',
    priority: 'Standard',
    biCreatedAt: '2024-11-01T09:00:00Z',
    biUpdatedAt: '2024-11-15T11:30:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-004',
      name: 'Pacific Surgical Associates',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@pacificsurgical.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-012',
        productName: 'Neuro Matrix Programmable Shunt System',
        sku: 'STR-NMTX-SHUNT',
        quantity: 12,
        unitPrice: 3200.0,
        discount: 0,
        lineTotal: 38400.0,
      },
    ],
    pricing: {
      subtotal: 38400.0,
      discount: 0,
      tax: 3264.0,
      freight: 350.0,
      total: 42014.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Pacific Surgical Associates',
      street: '900 Pacific Ave',
      building: 'Suite 200',
      city: 'Tacoma',
      state: 'WA',
      zip: '98402',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2024-11-20T00:00:00Z',
    contractId: null,
    notes: 'Cancelled — customer switched to competitor product.',
  },
  {
    biId: 'ORD-2025-0015',
    biName: 'Cascade Regional — Trauma Instruments',
    biDescription: 'Emergency trauma OR outfitting with power tools and fixation.',
    status: 'Draft',
    priority: 'Standard',
    biCreatedAt: '2025-01-15T08:00:00Z',
    biUpdatedAt: '2025-01-15T08:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-005',
      name: 'Cascade Regional Medical Center',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@cascaderegional.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'System 8 Large Bone Power Tool Set',
        sku: 'STR-8000-LB-SET',
        quantity: 3,
        unitPrice: 18750.0,
        discount: 0,
        lineTotal: 56250.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-019',
        productName: 'Hoffman 3 External Fixation System',
        sku: 'STR-HF3-EXFIX',
        quantity: 8,
        unitPrice: 3600.0,
        discount: 0,
        lineTotal: 28800.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-022',
        productName: 'System 8 SmartLife Battery Pack',
        sku: 'STR-8000-BATT',
        quantity: 12,
        unitPrice: 2850.0,
        discount: 0,
        lineTotal: 34200.0,
      },
    ],
    pricing: {
      subtotal: 119250.0,
      discount: 0,
      tax: 10136.25,
      freight: 1200.0,
      total: 130586.25,
      currency: 'USD',
    },
    shipTo: {
      name: 'Cascade Regional Medical Center',
      street: '2501 Mountain View Dr',
      building: 'Trauma Center',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-02-28T00:00:00Z',
    contractId: null,
    notes: 'Draft pending quote conversion. See QT-2025-0008.',
  },
];

export const getOrderById = (biId) => orders.find((o) => o.biId === biId);
export const getOrdersByStatus = (status) => orders.filter((o) => o.status === status);
export const getOrdersByCustomer = (customerId) =>
  orders.filter((o) => o.customer.id === customerId);

export const orderStatuses = [
  'Draft',
  'Submitted',
  'Confirmed',
  'Shipped',
  'Delivered',
  'Invoiced',
  'Cancelled',
];

export default orders;
