// Mock organizations/parties for Stryker B2B Portal
// Types: hospital, hospital_group, distributor, manufacturer, surgical_center

export const parties = [
  {
    id: 'ORG-001',
    name: 'Northwest Medical Center',
    type: 'hospital',
    taxId: '91-1234567',
    dunsNumber: '012345678',
    website: 'https://www.northwestmedical.org',
    primaryContact: {
      name: 'Dr. Sarah Chen',
      title: 'Chief of Orthopedic Surgery',
      email: 'sarah.chen@northwestmedical.org',
      phone: '+1 (206) 555-0142',
    },
    billingContact: {
      name: 'Karen Liu',
      title: 'Accounts Payable Manager',
      email: 'ap@northwestmedical.org',
      phone: '+1 (206) 555-0155',
    },
    addresses: {
      headquarters: {
        street: '1200 Madison Ave',
        city: 'Seattle',
        state: 'WA',
        zip: '98104',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-NWM-01',
          label: 'Main Receiving',
          street: '1200 Madison Ave',
          building: 'Facilities Receiving, Dock A',
          city: 'Seattle',
          state: 'WA',
          zip: '98104',
          country: 'US',
          isDefault: true,
        },
        {
          id: 'SHIP-NWM-02',
          label: 'Surgical Services',
          street: '1200 Madison Ave',
          building: 'Surgical Pavilion, Dock B',
          city: 'Seattle',
          state: 'WA',
          zip: '98104',
          country: 'US',
          isDefault: false,
        },
      ],
    },
    classification: {
      bedCount: 450,
      traumaLevel: 'Level I',
      teachingStatus: 'Academic Medical Center',
      gpoAffiliation: 'Premier Inc.',
      idnAffiliation: null,
    },
    contractIds: ['CTR-NWM-2024-001'],
    paymentTerms: 'Net 60',
    creditLimit: 5000000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2019-06-15T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-002',
    name: 'MedSupply Pro Distribution',
    type: 'distributor',
    taxId: '36-9876543',
    dunsNumber: '987654321',
    website: 'https://www.medsupplypro.com',
    primaryContact: {
      name: 'James Mitchell',
      title: 'Procurement Director',
      email: 'j.mitchell@medsupplypro.com',
      phone: '+1 (312) 555-0287',
    },
    billingContact: {
      name: 'Patricia Gomez',
      title: 'Finance Director',
      email: 'finance@medsupplypro.com',
      phone: '+1 (312) 555-0290',
    },
    addresses: {
      headquarters: {
        street: '4500 W Diversey Ave',
        city: 'Chicago',
        state: 'IL',
        zip: '60639',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-MSP-01',
          label: 'Main Warehouse',
          street: '4500 W Diversey Ave',
          building: 'Building C, Dock 4',
          city: 'Chicago',
          state: 'IL',
          zip: '60639',
          country: 'US',
          isDefault: true,
        },
        {
          id: 'SHIP-MSP-02',
          label: 'East Coast Warehouse',
          street: '200 Industrial Pkwy',
          city: 'Edison',
          state: 'NJ',
          zip: '08817',
          country: 'US',
          isDefault: false,
        },
      ],
    },
    classification: {
      distributorTier: 'Tier 1 — National',
      territories: ['Midwest', 'Northeast', 'Southeast'],
      resaleCertificate: 'RC-IL-2024-78901',
      taxExempt: true,
    },
    contractIds: ['CTR-MSP-2024-007'],
    paymentTerms: 'Net 30',
    creditLimit: 2000000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2018-03-01T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-003',
    name: 'Mercy Health System',
    type: 'hospital_group',
    taxId: '31-5678901',
    dunsNumber: '567890123',
    website: 'https://www.mercyhealth.org',
    primaryContact: {
      name: 'Michael Thompson',
      title: 'VP of Supply Chain',
      email: 'm.thompson@mercyhealth.org',
      phone: '+1 (513) 555-0361',
    },
    billingContact: {
      name: 'Robert Daniels',
      title: 'Director of Finance',
      email: 'r.daniels@mercyhealth.org',
      phone: '+1 (513) 555-0375',
    },
    addresses: {
      headquarters: {
        street: '615 Elsinore Pl',
        city: 'Cincinnati',
        state: 'OH',
        zip: '45202',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-MHS-01',
          label: 'Mercy West Hospital',
          street: '615 Elsinore Pl',
          building: 'Central Warehouse',
          city: 'Cincinnati',
          state: 'OH',
          zip: '45202',
          country: 'US',
          isDefault: true,
        },
        {
          id: 'SHIP-MHS-02',
          label: 'Mercy Fairfield Hospital',
          street: '3000 Mack Rd',
          building: 'Receiving Dock',
          city: 'Fairfield',
          state: 'OH',
          zip: '45014',
          country: 'US',
          isDefault: false,
        },
        {
          id: 'SHIP-MHS-03',
          label: 'Mercy Anderson Hospital',
          street: '7500 State Rd',
          building: 'Receiving',
          city: 'Anderson',
          state: 'OH',
          zip: '45230',
          country: 'US',
          isDefault: false,
        },
      ],
    },
    classification: {
      facilityCount: 3,
      totalBedCount: 850,
      gpoAffiliation: 'Vizient',
      idnAffiliation: 'Mercy Health Partners',
      teachingStatus: 'Community Teaching',
    },
    contractIds: ['CTR-MHS-2024-003'],
    paymentTerms: 'Net 45',
    creditLimit: 3000000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2020-01-10T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-004',
    name: 'Pacific Surgical Associates',
    type: 'surgical_center',
    taxId: '91-2345678',
    dunsNumber: '234567890',
    website: 'https://www.pacificsurgical.com',
    primaryContact: {
      name: 'Dr. Robert Kim',
      title: 'Medical Director',
      email: 'r.kim@pacificsurgical.com',
      phone: '+1 (253) 555-0198',
    },
    billingContact: {
      name: 'Jennifer Walsh',
      title: 'Office Manager',
      email: 'billing@pacificsurgical.com',
      phone: '+1 (253) 555-0200',
    },
    addresses: {
      headquarters: {
        street: '900 Pacific Ave',
        suite: 'Suite 200',
        city: 'Tacoma',
        state: 'WA',
        zip: '98402',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-PSA-01',
          label: 'Main Facility',
          street: '900 Pacific Ave',
          building: 'Suite 200, Receiving',
          city: 'Tacoma',
          state: 'WA',
          zip: '98402',
          country: 'US',
          isDefault: true,
        },
      ],
    },
    classification: {
      operatingRooms: 4,
      specialties: ['Orthopedics', 'Neurosurgery', 'Spine'],
      accreditation: 'AAAHC',
    },
    contractIds: [],
    paymentTerms: 'Net 30',
    creditLimit: 500000.0,
    creditStatus: 'Under Review',
    accountStatus: 'Active',
    createdAt: '2021-09-20T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-005',
    name: 'Cascade Regional Medical Center',
    type: 'hospital',
    taxId: '93-3456789',
    dunsNumber: '345678901',
    website: 'https://www.cascaderegional.org',
    primaryContact: {
      name: 'Dr. Amanda Foster',
      title: 'Chief Medical Officer',
      email: 'a.foster@cascaderegional.org',
      phone: '+1 (541) 555-0130',
    },
    billingContact: {
      name: 'Steven Moore',
      title: 'CFO',
      email: 's.moore@cascaderegional.org',
      phone: '+1 (541) 555-0135',
    },
    addresses: {
      headquarters: {
        street: '2501 Mountain View Dr',
        city: 'Bend',
        state: 'OR',
        zip: '97701',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-CRM-01',
          label: 'Main Hospital',
          street: '2501 Mountain View Dr',
          building: 'Receiving Dock',
          city: 'Bend',
          state: 'OR',
          zip: '97701',
          country: 'US',
          isDefault: true,
        },
      ],
    },
    classification: {
      bedCount: 180,
      traumaLevel: 'Level II',
      teachingStatus: 'Community Hospital',
      gpoAffiliation: 'HealthTrust',
      idnAffiliation: null,
    },
    contractIds: ['CTR-CRM-2024-001'],
    paymentTerms: 'Net 45',
    creditLimit: 1000000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2022-04-01T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-006',
    name: 'Stryker Corporation',
    type: 'manufacturer',
    taxId: '38-1239420',
    dunsNumber: '005168640',
    website: 'https://www.stryker.com',
    primaryContact: {
      name: 'Emily Rodriguez',
      title: 'Regional Sales Manager — Pacific Northwest',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    billingContact: null,
    addresses: {
      headquarters: {
        street: '2825 Airview Blvd',
        city: 'Kalamazoo',
        state: 'MI',
        zip: '49002',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-STR-01',
          label: 'Distribution Center — East',
          street: '1000 Stryker Way',
          city: 'Portage',
          state: 'MI',
          zip: '49002',
          country: 'US',
          isDefault: true,
        },
        {
          id: 'SHIP-STR-02',
          label: 'Distribution Center — West',
          street: '5900 Optical Ct',
          city: 'San Jose',
          state: 'CA',
          zip: '95138',
          country: 'US',
          isDefault: false,
        },
      ],
    },
    classification: {
      fortune500Rank: 172,
      employees: 51000,
      divisions: ['CMF', 'Endoscopy', 'Healthcare Systems, MedSurg', 'Instruments', 'Medical', 'Neurovascular', 'Performance Solutions', 'Reconstructive', 'Spine', 'Sustainability Solutions', 'Trauma & Extremities'],
      stockTicker: 'SYK',
      exchange: 'NYSE',
    },
    contractIds: [],
    paymentTerms: null,
    creditLimit: null,
    creditStatus: null,
    accountStatus: 'Active',
    createdAt: '2018-01-01T00:00:00Z',
    salesRepId: null,
  },
];

export const getPartyById = (id) => parties.find((p) => p.id === id);
export const getPartiesByType = (type) => parties.filter((p) => p.type === type);

export const partyTypes = [
  'hospital',
  'hospital_group',
  'distributor',
  'manufacturer',
  'surgical_center',
];

export default parties;
