// Mock quotes for Stryker B2B Portal
// Statuses: Draft, Submitted, Approved, Rejected, Converted

export const quotes = [
  {
    biId: 'QT-2025-0001',
    biName: 'Northwest Medical — Robotic Surgery Expansion',
    biDescription: 'Comprehensive quote for Mako system with training and first-year consumables.',
    status: 'Converted',
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-014',
        productName: 'Mako SmartRobotics System',
        quantity: 1,
        unitPrice: 1250000.0,
        discount: 50000.0,
        lineTotal: 1200000.0,
        notes: 'TKA + THA Application Bundle',
      },
    ],
    pricing: {
      subtotal: 1200000.0,
      discount: 50000.0,
      tax: 102000.0,
      freight: 8500.0,
      total: 1310500.0,
      currency: 'USD',
    },
    validFrom: '2024-12-01T00:00:00Z',
    validUntil: '2025-02-28T00:00:00Z',
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2025-01-02T09:15:00Z',
    convertedToOrderId: 'ORD-2025-0001',
    contractId: 'CTR-NWM-2024-001',
    termsAndConditions: 'Standard Stryker Capital Equipment Terms. Installation included. 2-year warranty.',
    notes: 'Converted to order ORD-2025-0001 on Jan 2, 2025.',
  },
  {
    biId: 'QT-2025-0002',
    biName: 'Mercy Health — Bed Replacement Phase 2',
    biDescription: 'Phase 2 of hospital bed replacement program for Mercy Fairfield Hospital.',
    status: 'Approved',
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-004',
        productName: 'Secure II Hospital Bed',
        quantity: 45,
        unitPrice: 14800.0,
        discount: 1850.0,
        lineTotal: 582750.0,
        notes: 'Med-Surg Configuration with mattress',
      },
      {
        lineNumber: 2,
        productId: 'PRD-005',
        productName: 'SAGE Prevalon Turn and Position System',
        quantity: 45,
        unitPrice: 4250.0,
        discount: 425.0,
        lineTotal: 172125.0,
        notes: 'One per bed — initial stock',
      },
    ],
    pricing: {
      subtotal: 754875.0,
      discount: 102375.0,
      tax: 55462.5,
      freight: 8200.0,
      total: 716162.5,
      currency: 'USD',
    },
    validFrom: '2025-01-01T00:00:00Z',
    validUntil: '2025-03-31T00:00:00Z',
    createdAt: '2025-01-03T14:00:00Z',
    updatedAt: '2025-01-10T11:30:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-MHS-2024-003',
    termsAndConditions: 'GPO pricing tier 2. Installation and bed removal of existing units included.',
    notes: 'Approved by VP Supply Chain. Awaiting PO from Mercy Fairfield.',
  },
  {
    biId: 'QT-2025-0003',
    biName: 'MedSupply Pro — Q1 2025 Distributor Restock',
    biDescription: 'Quarterly distributor bulk pricing proposal for surgical instruments and consumables.',
    status: 'Submitted',
    customer: {
      id: 'ORG-002',
      name: 'MedSupply Pro Distribution',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@medsupplypro.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'System 8 Large Bone Power Tool Set',
        quantity: 15,
        unitPrice: 18750.0,
        discount: 2812.5,
        lineTotal: 239062.5,
      },
      {
        lineNumber: 2,
        productId: 'PRD-002',
        productName: 'System 8 Small Bone Power Tool Set',
        quantity: 15,
        unitPrice: 15200.0,
        discount: 2280.0,
        lineTotal: 193800.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-022',
        productName: 'System 8 SmartLife Battery Pack',
        quantity: 60,
        unitPrice: 2850.0,
        discount: 427.5,
        lineTotal: 145350.0,
      },
      {
        lineNumber: 4,
        productId: 'PRD-005',
        productName: 'SAGE Prevalon Turn and Position System',
        quantity: 200,
        unitPrice: 4250.0,
        discount: 850.0,
        lineTotal: 680000.0,
      },
    ],
    pricing: {
      subtotal: 1258212.5,
      discount: 195712.5,
      tax: 0.0,
      freight: 5600.0,
      total: 1068100.0,
      currency: 'USD',
    },
    validFrom: '2025-01-15T00:00:00Z',
    validUntil: '2025-03-15T00:00:00Z',
    createdAt: '2025-01-12T09:00:00Z',
    updatedAt: '2025-01-12T09:00:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-MSP-2024-007',
    termsAndConditions: 'Distributor Tier 1 pricing. Volume discount applied. Tax exempt — resale.',
    notes: 'Submitted to James Mitchell for review. 15% volume discount proposed.',
  },
  {
    biId: 'QT-2025-0004',
    biName: 'Pacific Surgical — Navigation System',
    biDescription: 'Target X Navigation System evaluation proposal for spine surgery program.',
    status: 'Draft',
    customer: {
      id: 'ORG-004',
      name: 'Pacific Surgical Associates',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@pacificsurgical.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-011',
        productName: 'Target X Surgical Navigation System',
        quantity: 1,
        unitPrice: 285000.0,
        discount: 0,
        lineTotal: 285000.0,
        notes: 'Spine software suite only — cranial upgrade available',
      },
    ],
    pricing: {
      subtotal: 285000.0,
      discount: 0,
      tax: 24225.0,
      freight: 3500.0,
      total: 312725.0,
      currency: 'USD',
    },
    validFrom: '2025-01-15T00:00:00Z',
    validUntil: '2025-04-15T00:00:00Z',
    createdAt: '2025-01-14T16:30:00Z',
    updatedAt: '2025-01-14T16:30:00Z',
    convertedToOrderId: null,
    contractId: null,
    termsAndConditions: 'Standard Stryker Capital Equipment Terms. 90-day evaluation period available.',
    notes: 'Draft — awaiting clinical evaluation feedback from Dr. Kim.',
  },
  {
    biId: 'QT-2025-0005',
    biName: 'Cascade Regional — Joint Replacement Program',
    biDescription: 'Comprehensive joint replacement program including Triathlon Knee and Accolade Hip systems.',
    status: 'Approved',
    customer: {
      id: 'ORG-005',
      name: 'Cascade Regional Medical Center',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@cascaderegional.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-015',
        productName: 'Triathlon Total Knee System',
        quantity: 30,
        unitPrice: 8500.0,
        discount: 850.0,
        lineTotal: 229500.0,
        notes: 'CR and PS Bearing mix',
      },
      {
        lineNumber: 2,
        productId: 'PRD-016',
        productName: 'Accolade II Femoral Hip Stem',
        quantity: 20,
        unitPrice: 5200.0,
        discount: 520.0,
        lineTotal: 93600.0,
        notes: 'Standard and lateralized offset mix',
      },
      {
        lineNumber: 3,
        productId: 'PRD-008',
        productName: 'Trident II Acetabular System',
        quantity: 20,
        unitPrice: 6800.0,
        discount: 680.0,
        lineTotal: 122400.0,
        notes: 'X3 HXLPE bearing',
      },
    ],
    pricing: {
      subtotal: 445500.0,
      discount: 41000.0,
      tax: 34382.5,
      freight: 2800.0,
      total: 441682.5,
      currency: 'USD',
    },
    validFrom: '2025-01-05T00:00:00Z',
    validUntil: '2025-04-05T00:00:00Z',
    createdAt: '2025-01-05T11:00:00Z',
    updatedAt: '2025-01-13T15:45:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-CRM-2024-001',
    termsAndConditions: 'GPO pricing. Consignment stocking option available.',
    notes: 'Approved. PO expected by end of January.',
  },
  {
    biId: 'QT-2024-0006',
    biName: 'Mercy Health — Neurosurgery Equipment',
    biDescription: 'Sonopet iQ and navigation equipment for neurosurgery department.',
    status: 'Rejected',
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-010',
        productName: 'Sonopet iQ Ultrasonic Aspirator',
        quantity: 3,
        unitPrice: 67500.0,
        discount: 0,
        lineTotal: 202500.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-011',
        productName: 'Target X Surgical Navigation System',
        quantity: 1,
        unitPrice: 285000.0,
        discount: 0,
        lineTotal: 285000.0,
      },
    ],
    pricing: {
      subtotal: 487500.0,
      discount: 0,
      tax: 41437.5,
      freight: 5200.0,
      total: 534137.5,
      currency: 'USD',
    },
    validFrom: '2024-10-01T00:00:00Z',
    validUntil: '2024-12-31T00:00:00Z',
    createdAt: '2024-10-01T09:30:00Z',
    updatedAt: '2024-11-20T14:00:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-MHS-2024-003',
    termsAndConditions: 'Standard Capital Equipment Terms.',
    notes: 'Rejected — budget constraints. Customer requested revised quote with phased approach for FY2025.',
  },
  {
    biId: 'QT-2025-0007',
    biName: 'Northwest Medical — Neurovascular Consignment',
    biDescription: 'Consignment stock proposal for Surpass Evolve flow diverters.',
    status: 'Submitted',
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-013',
        productName: 'Surpass Evolve Flow Diverter',
        quantity: 20,
        unitPrice: 12500.0,
        discount: 1250.0,
        lineTotal: 225000.0,
        notes: 'Consignment stock — billed on usage',
      },
    ],
    pricing: {
      subtotal: 225000.0,
      discount: 25000.0,
      tax: 17000.0,
      freight: 0.0,
      total: 217000.0,
      currency: 'USD',
    },
    validFrom: '2025-01-10T00:00:00Z',
    validUntil: '2025-04-10T00:00:00Z',
    createdAt: '2025-01-10T13:00:00Z',
    updatedAt: '2025-01-10T13:00:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-NWM-2024-001',
    termsAndConditions: 'Consignment Agreement Terms. Quarterly audit required. 12-month shelf life minimum.',
    notes: 'Consignment model — bill on use. Quarterly inventory reconciliation.',
  },
  {
    biId: 'QT-2025-0008',
    biName: 'Cascade Regional — Trauma OR Outfitting',
    biDescription: 'Complete trauma OR setup with power tools and external fixation.',
    status: 'Draft',
    customer: {
      id: 'ORG-005',
      name: 'Cascade Regional Medical Center',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@cascaderegional.org',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@stryker.com',
      phone: '+1 (269) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'System 8 Large Bone Power Tool Set',
        quantity: 3,
        unitPrice: 18750.0,
        discount: 0,
        lineTotal: 56250.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-019',
        productName: 'Hoffman 3 External Fixation System',
        quantity: 8,
        unitPrice: 3600.0,
        discount: 0,
        lineTotal: 28800.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-022',
        productName: 'System 8 SmartLife Battery Pack',
        quantity: 12,
        unitPrice: 2850.0,
        discount: 0,
        lineTotal: 34200.0,
      },
    ],
    pricing: {
      subtotal: 119250.0,
      discount: 0,
      tax: 10136.25,
      freight: 1200.0,
      total: 130586.25,
      currency: 'USD',
    },
    validFrom: '2025-01-15T00:00:00Z',
    validUntil: '2025-04-15T00:00:00Z',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z',
    convertedToOrderId: null,
    contractId: null,
    termsAndConditions: 'Standard Terms. Volume discount to be negotiated.',
    notes: 'Draft — linked to ORD-2025-0015. Pending pricing review.',
  },
];

export const getQuoteById = (biId) => quotes.find((q) => q.biId === biId);
export const getQuotesByStatus = (status) => quotes.filter((q) => q.status === status);
export const getQuotesByCustomer = (customerId) =>
  quotes.filter((q) => q.customer.id === customerId);

export const quoteStatuses = ['Draft', 'Submitted', 'Approved', 'Rejected', 'Converted'];

export default quotes;
