// Mock RMA (Return Merchandise Authorization) records for Stryker B2B Portal
// Statuses: Requested, Approved, In Transit, Received, Inspected, Credited, Denied

export const returns = [
  {
    id: 'RMA-2025-0001',
    orderId: 'ORD-2025-0003',
    status: 'Approved',
    type: 'Defective',
    requestDate: '2025-01-05T10:00:00Z',
    approvedDate: '2025-01-07T14:30:00Z',
    receivedDate: null,
    resolvedDate: null,
    customer: {
      id: 'ORG-002',
      name: 'MedSupply Pro Distribution',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@medsupplypro.com',
    },
    items: [
      {
        productId: 'PRD-022',
        productName: 'System 8 SmartLife Battery Pack',
        serialNumber: 'BATT-2024-99034',
        quantity: 2,
        reason: 'Battery not holding charge — fails to reach full capacity after multiple charge cycles.',
        unitValue: 2850.0,
      },
    ],
    returnShipment: {
      carrier: 'FedEx',
      trackingNumber: null,
      labelProvided: true,
      labelUrl: '/labels/rma/RMA-2025-0001.pdf',
    },
    resolution: {
      type: 'Replacement',
      creditAmount: null,
      replacementOrderId: null,
      notes: 'Approved for replacement. Prepaid return label sent. Replace with current production lot upon receipt.',
    },
    shipFromAddress: {
      name: 'MedSupply Pro — Main Warehouse',
      street: '4500 W Diversey Ave',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
    },
    shipToAddress: {
      name: 'Stryker Returns Center',
      street: '2600 Commerce Dr',
      city: 'Portage',
      state: 'MI',
      zip: '49002',
    },
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Customer reported 2 of 40 batteries from ORD-2025-0003 defective. Lot BATT-LOT-2024-0921.',
  },
  {
    id: 'RMA-2024-0002',
    orderId: null,
    status: 'Credited',
    type: 'Warranty',
    requestDate: '2024-11-10T09:00:00Z',
    approvedDate: '2024-11-12T11:00:00Z',
    receivedDate: '2024-11-20T14:00:00Z',
    resolvedDate: '2024-12-05T10:30:00Z',
    customer: {
      id: 'ORG-005',
      name: 'Cascade Regional Medical Center',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@cascaderegional.org',
    },
    items: [
      {
        productId: 'PRD-001',
        productName: 'System 8 Large Bone Power Tool Set',
        serialNumber: 'S8LB-2021-33012',
        quantity: 1,
        reason: 'Oscillating saw motor failure — unit out of warranty but known manufacturing defect (TSB-2024-017).',
        unitValue: 3200.0,
      },
    ],
    returnShipment: {
      carrier: 'FedEx',
      trackingNumber: '7489 3301 8890',
      labelProvided: true,
      labelUrl: '/labels/rma/RMA-2024-0002.pdf',
    },
    resolution: {
      type: 'Credit',
      creditAmount: 3200.0,
      replacementOrderId: null,
      notes: 'Motor replaced on-site per SRV-2024-0018. Credit issued for repair cost per TSB-2024-017 goodwill policy.',
    },
    shipFromAddress: {
      name: 'Cascade Regional Medical Center',
      street: '2501 Mountain View Dr',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
    },
    shipToAddress: {
      name: 'Stryker Returns Center',
      street: '2600 Commerce Dr',
      city: 'Portage',
      state: 'MI',
      zip: '49002',
    },
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Goodwill credit applied — known defect per TSB-2024-017. Motor returned for root cause analysis.',
  },
  {
    id: 'RMA-2025-0003',
    orderId: 'ORD-2025-0002',
    status: 'Requested',
    type: 'Wrong Item',
    requestDate: '2025-01-12T16:00:00Z',
    approvedDate: null,
    receivedDate: null,
    resolvedDate: null,
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    items: [
      {
        productId: 'PRD-015',
        productName: 'Triathlon Total Knee System',
        serialNumber: 'TRI-2024-88045',
        quantity: 2,
        reason: 'Received Size 7 Right — ordered Size 5 Left. Packaging confirmed Size 5 Left but contents are Size 7 Right.',
        unitValue: 8500.0,
      },
    ],
    returnShipment: {
      carrier: null,
      trackingNumber: null,
      labelProvided: false,
      labelUrl: null,
    },
    resolution: {
      type: null,
      creditAmount: null,
      replacementOrderId: null,
      notes: 'Pending review — quality team to verify packaging error. Do not open sealed trays.',
    },
    shipFromAddress: {
      name: 'Mercy West Hospital — Central Supply',
      street: '615 Elsinore Pl',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
    },
    shipToAddress: null,
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Urgent — surgeon needs correct implants for scheduled procedure Jan 20. Expedite review.',
  },
  {
    id: 'RMA-2024-0004',
    orderId: null,
    status: 'Inspected',
    type: 'Damaged in Transit',
    requestDate: '2024-12-20T08:30:00Z',
    approvedDate: '2024-12-20T15:00:00Z',
    receivedDate: '2025-01-03T10:00:00Z',
    resolvedDate: null,
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    items: [
      {
        productId: 'PRD-005',
        productName: 'SAGE Prevalon Turn and Position System',
        serialNumber: null,
        batchNumber: 'SAGE-LOT-2024-0502',
        quantity: 5,
        reason: 'Outer packaging crushed during shipping. Inner sterile barrier compromised on 5 units.',
        unitValue: 4250.0,
      },
    ],
    returnShipment: {
      carrier: 'FedEx',
      trackingNumber: '7489 4401 2234',
      labelProvided: true,
      labelUrl: '/labels/rma/RMA-2024-0004.pdf',
    },
    resolution: {
      type: 'Replacement',
      creditAmount: null,
      replacementOrderId: null,
      notes: 'Received and inspected. Sterile barrier breach confirmed on 5 units. Replacement shipment being prepared. Carrier freight claim filed.',
    },
    shipFromAddress: {
      name: 'Northwest Medical Center — Central Supply',
      street: '1200 Madison Ave',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
    },
    shipToAddress: {
      name: 'Stryker Returns Center',
      street: '2600 Commerce Dr',
      city: 'Portage',
      state: 'MI',
      zip: '49002',
    },
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Freight claim filed with FedEx. Photos of damage on file.',
  },
  {
    id: 'RMA-2024-0005',
    orderId: null,
    status: 'Denied',
    type: 'Overstock Return',
    requestDate: '2024-10-15T11:00:00Z',
    approvedDate: null,
    receivedDate: null,
    resolvedDate: '2024-10-20T09:00:00Z',
    customer: {
      id: 'ORG-004',
      name: 'Pacific Surgical Associates',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@pacificsurgical.com',
    },
    items: [
      {
        productId: 'PRD-009',
        productName: 'SpinalPak Non-Invasive Spine Fusion Stimulator',
        serialNumber: 'SPAK-2024-66001',
        quantity: 3,
        reason: 'Overstock — purchased in excess of patient demand. Requesting return for credit.',
        unitValue: 5400.0,
      },
    ],
    returnShipment: {
      carrier: null,
      trackingNumber: null,
      labelProvided: false,
      labelUrl: null,
    },
    resolution: {
      type: 'Denied',
      creditAmount: 0,
      replacementOrderId: null,
      notes: 'Return denied — units are patient-specific prescription devices and beyond the 30-day return window. Recommend offering to other facilities in the area.',
    },
    shipFromAddress: null,
    shipToAddress: null,
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Denied per return policy Section 4.2 — prescription devices non-returnable after 30 days.',
  },
];

export const getReturnById = (id) => returns.find((r) => r.id === id);
export const getReturnsByStatus = (status) => returns.filter((r) => r.status === status);
export const getReturnsByCustomer = (customerId) =>
  returns.filter((r) => r.customer.id === customerId);

export const returnStatuses = [
  'Requested',
  'Approved',
  'In Transit',
  'Received',
  'Inspected',
  'Credited',
  'Denied',
];

export default returns;
