// Mock subscriptions for Stryker B2B Portal
// Statuses: Active, Paused, Cancelled

export const subscriptions = [
  {
    biId: 'SUB-001',
    biName: 'Neptune 3 Canister Auto-Replenishment',
    biDescription: 'Monthly auto-replenishment of Neptune 3 disposable canister sets for 4 systems.',
    product: {
      id: 'PRD-021',
      name: 'Neptune 3 Disposable Canister Set (Case of 12)',
      sku: 'STR-NEP3-CAN-12',
    },
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    frequency: 'Monthly',
    quantity: 8,
    unitPrice: 680.0,
    recurringTotal: 5440.0,
    currency: 'USD',
    nextDelivery: '2025-02-01T00:00:00Z',
    lastDelivery: '2025-01-02T00:00:00Z',
    startDate: '2024-12-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Northwest Medical Center — Central Supply',
      street: '1200 Madison Ave',
      building: 'Central Supply, Room B-104',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-NWM-2024-001',
    paymentTerms: 'Net 60',
    deliveriesCompleted: 2,
    notes: 'Linked to Neptune 3 installation (ORD-2025-0004). Review quantity at 6-month mark.',
  },
  {
    biId: 'SUB-002',
    biName: 'SAGE Prevalon Quarterly Restock',
    biDescription: 'Quarterly SAGE Prevalon system replenishment for ICU and Med-Surg floors.',
    product: {
      id: 'PRD-005',
      name: 'SAGE Prevalon Turn and Position System',
      sku: 'STR-SAGE-PTP-200',
    },
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    frequency: 'Quarterly',
    quantity: 50,
    unitPrice: 4250.0,
    recurringTotal: 212500.0,
    currency: 'USD',
    nextDelivery: '2025-04-01T00:00:00Z',
    lastDelivery: '2025-01-03T00:00:00Z',
    startDate: '2024-04-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Mercy Health System — Central Distribution',
      street: '615 Elsinore Pl',
      building: 'Central Warehouse',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-MHS-2024-003',
    paymentTerms: 'Net 45',
    deliveriesCompleted: 4,
    notes: 'Split delivery across 3 Mercy facilities per distribution list.',
  },
  {
    biId: 'SUB-003',
    biName: 'Sonopet iQ Tip Replenishment',
    biDescription: 'Monthly ultrasonic aspirator tip replacement for neurosurgery department.',
    product: {
      id: 'PRD-010',
      name: 'Sonopet iQ Ultrasonic Aspirator — Tip Kit',
      sku: 'STR-SPIQ-TIPS',
    },
    customer: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@northwestmedical.org',
    },
    frequency: 'Monthly',
    quantity: 4,
    unitPrice: 1250.0,
    recurringTotal: 5000.0,
    currency: 'USD',
    nextDelivery: '2025-02-01T00:00:00Z',
    lastDelivery: '2025-01-03T00:00:00Z',
    startDate: '2024-06-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Northwest Medical Center — Neuro OR',
      street: '1200 Madison Ave',
      building: 'Neuroscience Center, Floor 4, Sterile Processing',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-NWM-2024-001',
    paymentTerms: 'Net 60',
    deliveriesCompleted: 8,
    notes: 'Usage-based review semi-annually. Current tip set: neuro standard + tumor.',
  },
  {
    biId: 'SUB-004',
    biName: 'System 8 Battery Replacement Program',
    biDescription: 'Semi-annual battery pack replacement program for surgical instrument fleet.',
    product: {
      id: 'PRD-022',
      name: 'System 8 SmartLife Battery Pack',
      sku: 'STR-8000-BATT',
    },
    customer: {
      id: 'ORG-005',
      name: 'Cascade Regional Medical Center',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@cascaderegional.org',
    },
    frequency: 'Semi-Annual',
    quantity: 8,
    unitPrice: 2850.0,
    recurringTotal: 22800.0,
    currency: 'USD',
    nextDelivery: '2025-07-01T00:00:00Z',
    lastDelivery: '2025-01-05T00:00:00Z',
    startDate: '2024-01-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Cascade Regional Medical Center — Biomed',
      street: '2501 Mountain View Dr',
      building: 'Biomedical Engineering Dept',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-CRM-2024-001',
    paymentTerms: 'Net 45',
    deliveriesCompleted: 3,
    notes: 'Includes old battery return for recycling. Pre-paid return label enclosed.',
  },
  {
    biId: 'SUB-005',
    biName: 'Neptune 3 Canister — Mercy Health',
    biDescription: 'Bi-weekly Neptune 3 canister replenishment for high-volume OR.',
    product: {
      id: 'PRD-021',
      name: 'Neptune 3 Disposable Canister Set (Case of 12)',
      sku: 'STR-NEP3-CAN-12',
    },
    customer: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      contactName: 'Michael Thompson',
      contactEmail: 'm.thompson@mercyhealth.org',
    },
    frequency: 'Bi-Weekly',
    quantity: 6,
    unitPrice: 680.0,
    recurringTotal: 4080.0,
    currency: 'USD',
    nextDelivery: null,
    lastDelivery: '2024-11-15T00:00:00Z',
    startDate: '2024-06-01T00:00:00Z',
    endDate: '2024-12-01T00:00:00Z',
    status: 'Paused',
    deliveryAddress: {
      name: 'Mercy West Hospital — OR Supply',
      street: '615 Elsinore Pl',
      building: 'Surgical Services, Supply Room 2',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    autoRenew: false,
    contractId: 'CTR-MHS-2024-003',
    paymentTerms: 'Net 45',
    deliveriesCompleted: 12,
    notes: 'Paused — reviewing usage rates. Customer considering consolidation with SUB-002.',
  },
  {
    biId: 'SUB-006',
    biName: 'LIFEPAK Electrode Pads — Pacific Surgical',
    biDescription: 'Quarterly LIFEPAK defibrillator electrode pad replacement.',
    product: {
      id: 'PRD-007',
      name: 'LIFEPAK 15 Electrode Pads (10-pack)',
      sku: 'STR-LP15-PADS-10',
    },
    customer: {
      id: 'ORG-004',
      name: 'Pacific Surgical Associates',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@pacificsurgical.com',
    },
    frequency: 'Quarterly',
    quantity: 2,
    unitPrice: 450.0,
    recurringTotal: 900.0,
    currency: 'USD',
    nextDelivery: null,
    lastDelivery: '2024-07-01T00:00:00Z',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-09-30T00:00:00Z',
    status: 'Cancelled',
    deliveryAddress: {
      name: 'Pacific Surgical Associates',
      street: '900 Pacific Ave',
      building: 'Suite 200',
      city: 'Tacoma',
      state: 'WA',
      zip: '98402',
      country: 'US',
    },
    autoRenew: false,
    contractId: null,
    paymentTerms: 'Net 30',
    deliveriesCompleted: 3,
    notes: 'Cancelled — customer account under review due to overdue invoices.',
  },
];

export const getSubscriptionById = (biId) => subscriptions.find((s) => s.biId === biId);
export const getSubscriptionsByStatus = (status) =>
  subscriptions.filter((s) => s.status === status);
export const getSubscriptionsByCustomer = (customerId) =>
  subscriptions.filter((s) => s.customer.id === customerId);

export const subscriptionStatuses = ['Active', 'Paused', 'Cancelled'];

export default subscriptions;
