// Mock training resources for Stryker B2B Portal
// Types: Online Course, Video, Hands-On Workshop, Webinar, Certification, In-Service

export const training = [
  {
    id: 'TRN-001',
    title: 'Mako SmartRobotics TKA — Surgeon Certification Program',
    type: 'Certification',
    format: 'Hybrid (Online + Hands-On)',
    division: 'Reconstructive',
    productIds: ['PRD-014', 'PRD-015'],
    productNames: ['Mako SmartRobotics System', 'Triathlon Total Knee System'],
    description:
      'Comprehensive certification program for surgeons performing Mako robotic-arm assisted total knee arthroplasty. Includes online didactic modules, cadaver lab, and proctored cases.',
    duration: '3 days',
    durationMinutes: null,
    prerequisites: ['Board-certified orthopedic surgeon', 'Minimum 50 TKA cases'],
    learningObjectives: [
      'Master CT-based 3D preoperative planning',
      'Perform accurate patient registration',
      'Utilize AccuStop haptic guidance for bone preparation',
      'Manage intraoperative adjustments and soft tissue balancing',
      'Troubleshoot common system issues',
    ],
    instructor: {
      name: 'Dr. James Whitfield',
      title: 'Director of Robotic Surgery Education, Stryker',
    },
    nextAvailableDate: '2025-02-15T08:00:00Z',
    location: 'Stryker Education Center, Mahwah, NJ',
    maxParticipants: 8,
    currentEnrollment: 5,
    cmeCredits: 24,
    price: 0,
    priceNote: 'Complimentary with Mako system purchase',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-001',
    thumbnailUrl: '/images/training/mako-tka-cert.jpg',
    tags: ['mako', 'robotics', 'TKA', 'certification', 'surgeon', 'hands-on'],
  },
  {
    id: 'TRN-002',
    title: 'Neptune 3 — OR Staff In-Service Training',
    type: 'In-Service',
    format: 'On-Site',
    division: 'Healthcare Systems, MedSurg',
    productIds: ['PRD-003', 'PRD-021'],
    productNames: ['Neptune 3 Waste Management System', 'Neptune 3 Disposable Canister Set'],
    description:
      'On-site in-service training for OR nurses, surgical technologists, and environmental services staff on proper setup, operation, canister changes, and cleaning of the Neptune 3 system.',
    duration: '2 hours',
    durationMinutes: 120,
    prerequisites: [],
    learningObjectives: [
      'Properly set up Neptune 3 for surgical cases',
      'Safely change and dispose of canisters',
      'Perform daily cleaning and filter checks',
      'Respond to common alarms and error codes',
      'Understand closed-system waste management benefits',
    ],
    instructor: {
      name: 'Stryker Clinical Educator — Assigned at scheduling',
      title: null,
    },
    nextAvailableDate: '2025-01-25T06:00:00Z',
    location: 'On-site at customer facility',
    maxParticipants: 20,
    currentEnrollment: null,
    cmeCredits: 2,
    price: 0,
    priceNote: 'Included with Neptune 3 purchase',
    certificateIssued: true,
    enrollmentUrl: '/training/request/TRN-002',
    thumbnailUrl: '/images/training/neptune-3-inservice.jpg',
    tags: ['neptune', 'in-service', 'OR', 'nursing', 'waste-management'],
  },
  {
    id: 'TRN-003',
    title: 'Sonopet iQ — Advanced Neurosurgical Techniques',
    type: 'Hands-On Workshop',
    format: 'In-Person Lab',
    division: 'Instruments',
    productIds: ['PRD-010'],
    productNames: ['Sonopet iQ Ultrasonic Aspirator'],
    description:
      'Advanced cadaver-based workshop focusing on tissue-selective ultrasonic aspiration techniques for cranial and spinal tumor removal. Hands-on experience with all tip configurations.',
    duration: '1 day',
    durationMinutes: null,
    prerequisites: ['Neurosurgery residency or fellowship completed', 'Basic Sonopet familiarity'],
    learningObjectives: [
      'Select optimal tip configurations for different tissue types',
      'Utilize tissue-select technology for selective tumor removal',
      'Apply advanced aspiration techniques near critical structures',
      'Optimize iQ Intelligence module settings',
    ],
    instructor: {
      name: 'Dr. Patricia Nakamura',
      title: 'Associate Professor of Neurosurgery, University of Washington',
    },
    nextAvailableDate: '2025-03-08T08:00:00Z',
    location: 'Stryker Innovation Center, Flower Mound, TX',
    maxParticipants: 6,
    currentEnrollment: 3,
    cmeCredits: 8,
    price: 500.0,
    priceNote: 'Lab fee covers cadaver specimen and materials',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-003',
    thumbnailUrl: '/images/training/sonopet-iq-workshop.jpg',
    tags: ['sonopet', 'neurosurgery', 'hands-on', 'cadaver-lab', 'ultrasonic'],
  },
  {
    id: 'TRN-004',
    title: 'Secure II Hospital Bed — Biomedical Service Training',
    type: 'Online Course',
    format: 'Self-Paced Online',
    division: 'Medical',
    productIds: ['PRD-004'],
    productNames: ['Secure II Hospital Bed'],
    description:
      'Self-paced online training for biomedical engineers covering preventive maintenance procedures, diagnostic troubleshooting, electrical safety testing, and common repair procedures for the Secure II bed platform.',
    duration: '6 hours',
    durationMinutes: 360,
    prerequisites: ['Biomedical engineering background', 'Access to Secure II service manual'],
    learningObjectives: [
      'Perform comprehensive preventive maintenance inspections',
      'Diagnose and resolve common electrical and mechanical faults',
      'Conduct IEC 60601-1 electrical safety testing',
      'Replace major subassemblies (drive system, siderails, controls)',
      'Update bed firmware and software',
    ],
    instructor: null,
    nextAvailableDate: null,
    location: 'Online — Stryker Learning Portal',
    maxParticipants: null,
    currentEnrollment: null,
    cmeCredits: 6,
    price: 0,
    priceNote: 'Free for authorized service partners',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-004',
    thumbnailUrl: '/images/training/secure-ii-biomed.jpg',
    tags: ['hospital-bed', 'secure-ii', 'biomed', 'service', 'online', 'self-paced'],
  },
  {
    id: 'TRN-005',
    title: 'LIFEPAK 15 — Advanced Cardiac Life Support Integration',
    type: 'Webinar',
    format: 'Live Webinar',
    division: 'Medical',
    productIds: ['PRD-007'],
    productNames: ['LIFEPAK 15 Monitor/Defibrillator'],
    description:
      'Live webinar covering advanced LIFEPAK 15 features for ACLS providers, including 12-lead ECG interpretation workflows, trending data review, CODE-STAT data download, and integration with hospital EHR systems.',
    duration: '90 minutes',
    durationMinutes: 90,
    prerequisites: ['Current ACLS certification'],
    learningObjectives: [
      'Utilize advanced 12-lead acquisition and interpretation features',
      'Configure and review trending patient data',
      'Download and analyze case data via CODE-STAT',
      'Integrate LIFEPAK data with hospital information systems',
    ],
    instructor: {
      name: 'Sarah Blackwell, RN, CCRN',
      title: 'Clinical Education Specialist, Stryker Emergency Care',
    },
    nextAvailableDate: '2025-01-28T12:00:00Z',
    location: 'Online — Zoom Webinar',
    maxParticipants: 100,
    currentEnrollment: 42,
    cmeCredits: 1.5,
    price: 0,
    priceNote: 'Free — registration required',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-005',
    thumbnailUrl: '/images/training/lifepak-15-acls.jpg',
    tags: ['lifepak', 'defibrillator', 'ACLS', 'webinar', 'emergency', '12-lead'],
  },
  {
    id: 'TRN-006',
    title: 'Trauma & Extremities — VariAx and T2 Alpha Surgical Techniques',
    type: 'Video',
    format: 'On-Demand Video Series',
    division: 'Trauma & Extremities',
    productIds: ['PRD-017', 'PRD-018', 'PRD-019'],
    productNames: [
      'VariAx 2 Distal Radius Locking Plate System',
      'T2 Alpha Femoral Nailing System',
      'Hoffman 3 External Fixation System',
    ],
    description:
      'On-demand video series featuring expert surgeons demonstrating surgical techniques for Stryker trauma fixation products. Covers distal radius plating, femoral nailing, and external fixation applications.',
    duration: '4 hours (8 videos)',
    durationMinutes: 240,
    prerequisites: [],
    learningObjectives: [
      'Apply anatomic plating techniques for distal radius fractures',
      'Master femoral nail entry point selection and insertion',
      'Assemble and apply Hoffman 3 external fixation configurations',
      'Manage complex fracture patterns with combined fixation strategies',
    ],
    instructor: {
      name: 'Multiple Faculty',
      title: 'Stryker Trauma & Extremities Advisory Board',
    },
    nextAvailableDate: null,
    location: 'Online — Stryker Learning Portal',
    maxParticipants: null,
    currentEnrollment: null,
    cmeCredits: 4,
    price: 0,
    priceNote: 'Free for registered Stryker customers',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-006',
    thumbnailUrl: '/images/training/trauma-techniques.jpg',
    tags: ['trauma', 'surgical-technique', 'video', 'on-demand', 'fracture-fixation'],
  },
  {
    id: 'TRN-007',
    title: 'B2B Portal — Customer Ordering and Account Management',
    type: 'Online Course',
    format: 'Self-Paced Online',
    division: 'General',
    productIds: [],
    productNames: [],
    description:
      'Self-paced tutorial for new B2B portal users. Learn to navigate the portal, search products, place orders, track shipments, manage invoices, view consignment inventory, and manage subscriptions.',
    duration: '45 minutes',
    durationMinutes: 45,
    prerequisites: [],
    learningObjectives: [
      'Navigate the B2B portal dashboard and product catalog',
      'Place and track orders',
      'Manage invoices and payment information',
      'View and manage consignment inventory',
      'Set up and modify recurring subscriptions',
      'Submit service requests and RMAs',
    ],
    instructor: null,
    nextAvailableDate: null,
    location: 'Online — Stryker Learning Portal',
    maxParticipants: null,
    currentEnrollment: null,
    cmeCredits: 0,
    price: 0,
    priceNote: 'Free for all portal users',
    certificateIssued: false,
    enrollmentUrl: '/training/enroll/TRN-007',
    thumbnailUrl: '/images/training/b2b-portal-training.jpg',
    tags: ['portal', 'onboarding', 'ordering', 'self-paced', 'tutorial'],
  },
  {
    id: 'TRN-008',
    title: 'Joint Replacement — Mako THA Surgical Technique',
    type: 'Certification',
    format: 'Hybrid (Online + Hands-On)',
    division: 'Reconstructive',
    productIds: ['PRD-014', 'PRD-016', 'PRD-008'],
    productNames: ['Mako SmartRobotics System', 'Accolade II Femoral Hip Stem', 'Trident II Acetabular System'],
    description:
      'Surgeon certification for Mako robotic-arm assisted total hip arthroplasty. Covers CT planning for hip anatomy, acetabular and femoral registration, robotic bone preparation, and component placement with the Trident II and Accolade II systems.',
    duration: '2 days',
    durationMinutes: null,
    prerequisites: ['Board-certified orthopedic surgeon', 'Minimum 50 THA cases', 'Mako TKA certification recommended'],
    learningObjectives: [
      'Plan acetabular and femoral component positioning using CT-based 3D planning',
      'Perform patient registration for hip arthroplasty',
      'Execute robotic-assisted acetabular reaming and cup placement',
      'Utilize real-time feedback for leg length and offset management',
      'Manage hip stability intraoperatively',
    ],
    instructor: {
      name: 'Dr. James Whitfield',
      title: 'Director of Robotic Surgery Education, Stryker',
    },
    nextAvailableDate: '2025-03-22T08:00:00Z',
    location: 'Stryker Education Center, Mahwah, NJ',
    maxParticipants: 8,
    currentEnrollment: 2,
    cmeCredits: 16,
    price: 0,
    priceNote: 'Complimentary with Mako system purchase',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-008',
    thumbnailUrl: '/images/training/mako-tha-cert.jpg',
    tags: ['mako', 'robotics', 'THA', 'certification', 'surgeon', 'hip', 'hands-on'],
  },
];

export const getTrainingById = (id) => training.find((t) => t.id === id);
export const getTrainingByProduct = (productId) =>
  training.filter((t) => t.productIds.includes(productId));
export const getTrainingByType = (type) => training.filter((t) => t.type === type);
export const getTrainingByDivision = (division) =>
  training.filter((t) => t.division === division);

export const trainingTypes = [
  'Online Course',
  'Video',
  'Hands-On Workshop',
  'Webinar',
  'Certification',
  'In-Service',
];

export default training;
