// Mock users for Stryker B2B Portal
// Represents different customer roles and personas

export const users = [
  {
    id: 'USR-001',
    firstName: 'Sarah',
    lastName: 'Chen',
    fullName: 'Dr. Sarah Chen',
    email: 'sarah.chen@northwestmedical.org',
    phone: '+1 (206) 555-0142',
    role: 'medical_professional',
    title: 'Chief of Orthopedic Surgery',
    organization: {
      id: 'ORG-001',
      name: 'Northwest Medical Center',
      type: 'hospital',
      address: {
        street: '1200 Madison Ave',
        city: 'Seattle',
        state: 'WA',
        zip: '98104',
        country: 'US',
      },
    },
    permissions: [
      'view_products',
      'place_orders',
      'view_orders',
      'manage_consignment',
      'view_invoices',
      'request_quotes',
      'manage_assets',
      'submit_service_requests',
      'view_training',
    ],
    preferences: {
      defaultShipTo: 'SHIP-NWM-01',
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: false,
        orderUpdates: true,
        promotions: false,
      },
    },
    lastLogin: '2025-01-15T08:32:00Z',
    createdAt: '2023-06-10T14:00:00Z',
    isActive: true,
    avatar: '/avatars/sarah-chen.jpg',
  },
  {
    id: 'USR-002',
    firstName: 'James',
    lastName: 'Mitchell',
    fullName: 'James Mitchell',
    email: 'j.mitchell@medsupplypro.com',
    phone: '+1 (312) 555-0287',
    role: 'distributor',
    title: 'Procurement Director',
    organization: {
      id: 'ORG-002',
      name: 'MedSupply Pro Distribution',
      type: 'distributor',
      address: {
        street: '4500 W Diversey Ave',
        city: 'Chicago',
        state: 'IL',
        zip: '60639',
        country: 'US',
      },
    },
    permissions: [
      'view_products',
      'place_orders',
      'view_orders',
      'bulk_ordering',
      'view_invoices',
      'manage_invoices',
      'request_quotes',
      'view_pricing_tiers',
      'manage_returns',
      'view_training',
    ],
    preferences: {
      defaultShipTo: 'SHIP-MSP-01',
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: true,
        orderUpdates: true,
        promotions: true,
      },
    },
    lastLogin: '2025-01-14T16:45:00Z',
    createdAt: '2022-11-03T09:30:00Z',
    isActive: true,
    avatar: '/avatars/james-mitchell.jpg',
  },
  {
    id: 'USR-003',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    fullName: 'Emily Rodriguez',
    email: 'emily.rodriguez@stryker.com',
    phone: '+1 (269) 555-0193',
    role: 'sales_rep',
    title: 'Regional Sales Manager — Pacific Northwest',
    organization: {
      id: 'ORG-006',
      name: 'Stryker Corporation',
      type: 'manufacturer',
      address: {
        street: '2825 Airview Blvd',
        city: 'Kalamazoo',
        state: 'MI',
        zip: '49002',
        country: 'US',
      },
    },
    permissions: [
      'view_products',
      'view_all_orders',
      'manage_quotes',
      'view_all_invoices',
      'view_all_customers',
      'manage_pricing',
      'view_consignment',
      'manage_consignment',
      'view_assets',
      'manage_service_requests',
      'view_reports',
      'manage_training',
    ],
    territory: {
      region: 'Pacific Northwest',
      states: ['WA', 'OR', 'ID', 'MT'],
      accounts: ['ORG-001', 'ORG-004'],
    },
    preferences: {
      defaultShipTo: null,
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: true,
        orderUpdates: true,
        promotions: false,
      },
    },
    lastLogin: '2025-01-15T09:10:00Z',
    createdAt: '2021-03-15T10:00:00Z',
    isActive: true,
    avatar: '/avatars/emily-rodriguez.jpg',
  },
  {
    id: 'USR-004',
    firstName: 'Michael',
    lastName: 'Thompson',
    fullName: 'Michael Thompson',
    email: 'm.thompson@mercyhealth.org',
    phone: '+1 (513) 555-0361',
    role: 'hospital_group',
    title: 'VP of Supply Chain',
    organization: {
      id: 'ORG-003',
      name: 'Mercy Health System',
      type: 'hospital_group',
      address: {
        street: '615 Elsinore Pl',
        city: 'Cincinnati',
        state: 'OH',
        zip: '45202',
        country: 'US',
      },
    },
    permissions: [
      'view_products',
      'place_orders',
      'view_orders',
      'bulk_ordering',
      'view_invoices',
      'manage_invoices',
      'request_quotes',
      'manage_contracts',
      'manage_consignment',
      'manage_assets',
      'submit_service_requests',
      'view_reports',
      'view_training',
    ],
    managedFacilities: [
      { id: 'FAC-001', name: 'Mercy West Hospital', city: 'Cincinnati', state: 'OH' },
      { id: 'FAC-002', name: 'Mercy Fairfield Hospital', city: 'Fairfield', state: 'OH' },
      { id: 'FAC-003', name: 'Mercy Anderson Hospital', city: 'Anderson', state: 'OH' },
    ],
    preferences: {
      defaultShipTo: 'SHIP-MHS-01',
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: false,
        orderUpdates: true,
        promotions: false,
      },
    },
    lastLogin: '2025-01-13T11:20:00Z',
    createdAt: '2023-01-20T08:00:00Z',
    isActive: true,
    avatar: '/avatars/michael-thompson.jpg',
  },
];

export const getCurrentUser = (userId = 'USR-001') => {
  return users.find((u) => u.id === userId) || users[0];
};

export default users;
